# -*- coding: utf-8 -*-
"""C1 — Advanced curriculum data."""

OVERVIEW = ("C1 completes the subjunctive system with the trapassato and full sequence of "
            "tenses, adds the impossible-past conditional, the gerund and progressive form, "
            "pronominal verbs, and the discourse connectors and register choices that separate "
            "fluent Italian from merely correct Italian.")

LESSONS = [
    {
        "id": "c1-congiuntivo-trapassato",
        "level": "C1", "unit": "1", "order": 1, "skill": "grammar", "strand": "subjunctive",
        "title": "Il Congiuntivo Trapassato e la Concordanza dei Tempi",
        "subtitle": "The subjunctive's past-before-past tense, and the complete sequence-of-tenses picture.",
        "objectives": [
            "Form the congiuntivo trapassato",
            "Apply the full sequence-of-tenses table across all four subjunctive forms",
            "Use the congiuntivo trapassato for a completed action before a past main clause",
        ],
        "content": {
            "intro": "With the congiuntivo trapassato, Italian's subjunctive system is complete — four tenses (presente, passato, imperfetto, trapassato) that map cleanly onto the four indicative time frames.",
            "explanation": "<p>Formed with the congiuntivo imperfetto of avere/essere + past participle: <em>avessi parlato, fossi partito/a</em>. It expresses an action that had already happened before the time of a past main clause — the subjunctive counterpart of the trapassato prossimo.</p>",
            "table": "<div class=\"table-scroll\"><table class=\"ref-table\"><caption>Sequence of tenses (simplified, standard cases)</caption><thead><tr><th>Main clause</th><th>Same time / later</th><th>Earlier (already happened)</th></tr></thead><tbody><tr><td>Present/future</td><td>congiuntivo presente</td><td>congiuntivo passato</td></tr><tr><td>Past/conditional</td><td>congiuntivo imperfetto</td><td>congiuntivo trapassato</td></tr></tbody></table></div>",
            "rules": [
                {"heading": "a) Formation", "body": "<p>avessi/avessi/avesse/avessimo/aveste/avessero, or fossi/fossi/fosse/fossimo/foste/fossero, + past participle (agreeing with the subject when the auxiliary is essere).</p>"},
                {"heading": "b) Use", "body": "<p><em>Pensavo che avesse già finito.</em> (I thought he had already finished.) <em>Non credevo che fossero già partiti.</em> (I didn't think they had already left.)</p>"},
            ],
            "examples": [
                {"it": "Pensavo che aveste già mangiato.", "en": "I thought you had already eaten."},
                {"it": "Speravo che non fosse successo niente di grave.", "en": "I hoped nothing serious had happened."},
                {"it": "Non sapevo che si fossero già conosciuti.", "en": "I didn't know they had already met each other."},
                {"it": "Era il film più bello che avessi mai visto.", "en": "It was the best film I had ever seen."},
            ],
            "commonMistakes": [
                {"wrong": "Pensavo che avesse finito ieri. (needs already-completed nuance but uses the wrong tense)", "right": "Pensavo che avesse già finito.", "why": "An action completed before the past main clause needs the trapassato, matching the earlier-than-earlier timeline."},
                {"wrong": "Era il film più bello che ho mai visto.", "right": "Era il film più bello che avessi mai visto.", "why": "A superlative relative clause (\"the most... that...\") conventionally triggers the subjunctive in Italian, and past context calls for the trapassato here."},
            ],
        },
        "exercises": [
            {"id": "c1ct-fill", "type": "fill-blank", "title": "Fill in the Blanks",
             "items": [
                {"id": "c1ct1", "prompt": "Pensavo che tu ___ (già - partire).", "answers": [["fossi già partito", "fossi già partita"]], "explanation": "Congiuntivo trapassato of partire (essere).", "options": ["fossi già partito", "sia già partito", "eri già partito"]},
                {"id": "c1ct2", "prompt": "Non credevo che loro ___ (finire) il progetto così presto.", "answers": [["avessero finito"]], "explanation": "Congiuntivo trapassato of finire (avere).", "options": ["avessero finito", "abbiano finito", "avevano finito"]},
             ]},
            {"id": "c1ct-mc", "type": "multiple-choice", "title": "Choose the Correct Tense",
             "items": [
                {"id": "c1ct3", "prompt": "\"It was the hardest exam I had ever taken.\"", "options": ["che avevo mai fatto", "che avessi mai fatto", "che ho mai fatto"], "answerIndex": 1, "explanation": "Superlative relative clause in a past context → congiuntivo trapassato."},
             ]},
            {"id": "c1ct-fill2", "type": "fill-blank", "title": "More Congiuntivo Trapassato Practice",
             "items": [
                {"id": "c1ct4", "prompt": "Pensavo che loro ___ (già - arrivare).", "answers": [["fossero già arrivati", "fossero già arrivate"]], "explanation": "Congiuntivo trapassato of arrivare (essere), agreeing with the plural subject.", "options": ["fossero già arrivati", "erano già arrivati", "siano già arrivati"]},
                {"id": "c1ct5", "prompt": "Non sapevo che tu ___ (perdere) il lavoro.", "answers": [["avessi perso"]], "explanation": "Congiuntivo trapassato of perdere (avere).", "options": ["avessi perso", "hai perso", "avevi perso"]},
                {"id": "c1ct6", "prompt": "Speravo che voi ___ (finire) in tempo.", "answers": [["aveste finito"]], "explanation": "Congiuntivo trapassato of finire (avere), voi form.", "options": ["aveste finito", "abbiate finito", "avevate finito"]},
                {"id": "c1ct7", "prompt": "Era la cosa più strana che ___ (io - mai vedere).", "answers": [["avessi mai visto"]], "explanation": "Superlative relative clause in a past context.", "options": ["avessi mai visto", "ho mai visto", "avevo mai visto"]},
                {"id": "c1ct8", "prompt": "Credevo che lei ___ (già - partire).", "answers": [["fosse già partita"]], "explanation": "Congiuntivo trapassato of partire (essere), agreeing with the feminine subject.", "options": ["fosse già partita", "era già partita", "sia già partita"]},
                {"id": "c1ct9", "prompt": "Non pensavo che loro ___ (dire) la verità.", "answers": [["avessero detto"]], "explanation": "Congiuntivo trapassato of dire (avere).", "options": ["avessero detto", "hanno detto", "dicessero"]},
                {"id": "c1ct10", "prompt": "Avrei voluto che tu mi ___ (avvisare) prima.", "answers": [["avessi avvisato"]], "explanation": "Congiuntivo trapassato of avvisare (avere).", "options": ["avessi avvisato", "avvisassi", "hai avvisato"]},
                {"id": "c1ct11", "prompt": "Sembrava che nessuno ___ (capire) la domanda.", "answers": [["avesse capito"]], "explanation": "Congiuntivo trapassato of capire (avere).", "options": ["avesse capito", "ha capito", "capiva"]},
             ]},
            {"id": "c1ct-mc2", "type": "multiple-choice", "title": "More Sequence-of-Tenses Choices",
             "items": [
                {"id": "c1ct12", "prompt": "Which tense pairs with a present/future main clause for an earlier action?", "options": ["congiuntivo passato", "congiuntivo trapassato", "congiuntivo imperfetto"], "answerIndex": 0, "explanation": "Congiuntivo passato marks an earlier action under a present/future main clause."},
                {"id": "c1ct13", "prompt": "Which tense pairs with a past main clause for an earlier action?", "options": ["congiuntivo trapassato", "congiuntivo presente", "congiuntivo passato"], "answerIndex": 0, "explanation": "Congiuntivo trapassato marks an earlier action under a past main clause."},
                {"id": "c1ct14", "prompt": "\"Pensavo che avesse già finito\" means...", "options": ["I thought he had already finished.", "I think he has already finished.", "I thought he was finishing."], "answerIndex": 0, "explanation": "The trapassato marks completion before the past main clause."},
                {"id": "c1ct15", "prompt": "Which auxiliary tense forms the congiuntivo trapassato?", "options": ["congiuntivo imperfetto of avere/essere", "congiuntivo presente of avere/essere", "imperfetto indicativo of avere/essere"], "answerIndex": 0, "explanation": "The auxiliary itself is in the congiuntivo imperfetto."},
                {"id": "c1ct16", "prompt": "A superlative relative clause (\"the most... that\") conventionally triggers...", "options": ["the subjunctive", "the indicative", "the conditional"], "answerIndex": 0, "explanation": "This is a fixed pattern in Italian, unlike English."},
                {"id": "c1ct17", "prompt": "\"Non credevo che fossero già partiti\" — fossero agrees with...", "options": ["a plural subject", "a singular subject", "no particular subject"], "answerIndex": 0, "explanation": "Fossero is the loro form of the congiuntivo imperfetto of essere."},
                {"id": "c1ct18", "prompt": "Which sentence correctly uses the congiuntivo trapassato?", "options": ["Pensavo che avesse mangiato.", "Pensavo che abbia mangiato.", "Pensavo che mangiasse."], "answerIndex": 0, "explanation": "Avesse mangiato is the correct congiuntivo trapassato form."},
                {"id": "c1ct19", "prompt": "The congiuntivo trapassato completes the subjunctive system alongside which three other tenses?", "options": ["presente, passato, imperfetto", "presente, futuro, passato", "imperfetto, futuro, condizionale"], "answerIndex": 0, "explanation": "Together these four tenses map onto the indicative's time frames."},
             ]},
            {"id": "c1ct-tf", "type": "true-false", "title": "True or False?",
             "items": [
                {"id": "c1ct20", "statement": "The congiuntivo trapassato is formed with the congiuntivo imperfetto of avere/essere plus the past participle.", "answer": True, "explanation": "This is exactly how the tense is built."},
                {"id": "c1ct21", "statement": "The congiuntivo trapassato is used for an action happening at the same time as the main clause.", "answer": False, "explanation": "It marks an action that happened before the past main clause."},
                {"id": "c1ct22", "statement": "The four subjunctive tenses map onto the four indicative time frames.", "answer": True, "explanation": "Presente, passato, imperfetto and trapassato mirror the indicative system."},
                {"id": "c1ct23", "statement": "A completed action before a present-tense main clause uses the congiuntivo trapassato.", "answer": False, "explanation": "That case uses the congiuntivo passato; the trapassato pairs with a past main clause."},
                {"id": "c1ct24", "statement": "Fossi, fossi, fosse, fossimo, foste, fossero are the congiuntivo imperfetto forms of essere, used inside the trapassato.", "answer": True, "explanation": "These are essere's irregular imperfect subjunctive forms."},
                {"id": "c1ct25", "statement": "The participle never agrees with the subject in the congiuntivo trapassato, even with essere.", "answer": False, "explanation": "It agrees just like in the trapassato prossimo, when the auxiliary is essere."},
                {"id": "c1ct26", "statement": "\"Era il film più bello che avessi mai visto\" uses the trapassato because of the superlative + past context.", "answer": True, "explanation": "Superlative relative clauses in a past context conventionally take the trapassato."},
                {"id": "c1ct27", "statement": "The congiuntivo trapassato is only used in written Italian, never spoken.", "answer": False, "explanation": "It's used in everyday narrated speech whenever the context calls for it."},
             ]},
        ],
        "summary": [
            "Congiuntivo trapassato = congiuntivo imperfetto of avere/essere + past participle.",
            "Completes the four-tense subjunctive system, mirroring the indicative's time frames.",
            "Used for an action already completed before a past-tense (or conditional) main clause.",
        ],
    },
    {
        "id": "c1-periodo-ipotetico-terzo-tipo",
        "level": "C1", "unit": "1", "order": 2, "skill": "grammar", "strand": "conditionals",
        "title": "Il Periodo Ipotetico di Terzo Tipo",
        "subtitle": "\"If I had known...\" — the impossible past.",
        "objectives": [
            "Form the third type hypothetical sentence for the unreal past",
            "Use the condizionale passato in the main clause",
            "Recognize mixed hypotheticals (past condition, present consequence)",
        ],
        "content": {
            "intro": "The third type of hypothetical sentence talks about something that didn't happen in the past — and, by logical necessity, whose consequence also never happened.",
            "explanation": "<p>Se + congiuntivo trapassato, condizionale passato (avrei/sarei + past participle): <em>Se avessi saputo, sarei venuto.</em> (If I had known, I would have come — but I didn't know, and I didn't come.) Both halves describe a counterfactual past.</p>",
            "rules": [
                {"heading": "a) Formation", "body": "<p>se + avessi/fossi + participle, avrei/sarei + participle: <em>Se avessi studiato di più, avrei passato l'esame.</em></p>"},
                {"heading": "b) Mixed hypothetical", "body": "<p>A past condition can have a present consequence: <em>Se avessi accettato quel lavoro, ora vivrei a Milano.</em> (If I had accepted that job, I'd be living in Milan now.) — condizionale presente in the main clause, since the consequence is felt now, not back then.</p>"},
            ],
            "examples": [
                {"it": "Se avessi saputo, ti avrei chiamato subito.", "en": "If I had known, I would have called you right away."},
                {"it": "Se non avessimo perso il treno, saremmo già arrivati.", "en": "If we hadn't missed the train, we would already have arrived."},
                {"it": "Avrei accettato l'offerta se me l'avessero fatta prima.", "en": "I would have accepted the offer if they had made it to me sooner."},
                {"it": "Se mi fossi laureato in ingegneria, ora lavorerei in un'altra azienda.", "en": "If I had graduated in engineering, I'd be working at a different company now. (mixed)"},
            ],
            "commonMistakes": [
                {"wrong": "Se avrei saputo, sarei venuto.", "right": "Se avessi saputo, sarei venuto.", "why": "The se-clause needs the congiuntivo trapassato, never the conditional — same rule as the second type, one tense further back."},
                {"wrong": "Se avessi studiato di più, avessi passato l'esame.", "right": "Se avessi studiato di più, avrei passato l'esame.", "why": "The main clause needs the condizionale passato, not a repeated subjunctive."},
            ],
        },
        "exercises": [
            {"id": "c1pt-fill", "type": "fill-blank", "title": "Fill in the Blanks",
             "items": [
                {"id": "c1pt1", "prompt": "Se ___ (io - sapere), ti ___ (avvisare) subito.", "answers": [["avessi saputo"], ["avrei avvisato"]], "explanation": "Third type: congiuntivo trapassato + condizionale passato.", "options": ["avessi saputo", "sapevo", "avrei avvisato", "avvisavo"]},
                {"id": "c1pt2", "prompt": "Se non ___ (perdere) il volo, ___ (arrivare) in tempo.", "answers": [["avessimo perso"], ["saremmo arrivati", "saremmo arrivate"]], "explanation": "Third type, essere auxiliary in the main clause.", "options": ["avessimo perso", "abbiamo perso", "saremmo arrivati", "arriveremmo"]},
             ]},
            {"id": "c1pt-mc", "type": "multiple-choice", "title": "Choose the Correct Sentence",
             "items": [
                {"id": "c1pt3", "prompt": "\"If you had told me, I would have helped you.\"", "options": ["Se mi avresti detto, ti avrei aiutato.", "Se mi avessi detto, ti avrei aiutato.", "Se mi dicevi, ti aiutavo."], "answerIndex": 1, "explanation": "Se + congiuntivo trapassato, condizionale passato in the main clause."},
             ]},
            {"id": "c1pt-fill2", "type": "fill-blank", "title": "More Third-Type Practice",
             "items": [
                {"id": "c1pt4", "prompt": "Se ___ (io - studiare) di più, ___ (passare) l'esame.", "answers": [["avessi studiato"], ["avrei passato"]], "explanation": "Congiuntivo trapassato + condizionale passato.", "options": ["avessi studiato", "studiavo", "avrei passato", "passavo"]},
                {"id": "c1pt5", "prompt": "Se non ___ (loro - arrivare) in ritardo, ___ (vedere) l'inizio del film.", "answers": [["fossero arrivati"], ["avrebbero visto"]], "explanation": "Third type with essere in the se-clause.", "options": ["fossero arrivati", "arrivavano", "avrebbero visto", "vedevano"]},
                {"id": "c1pt6", "prompt": "Se mi ___ (tu - chiedere) aiuto, te lo ___ (dare) volentieri.", "answers": [["avessi chiesto"], ["avrei dato"]], "explanation": "Third type, both halves counterfactual.", "options": ["avessi chiesto", "chiedevi", "avrei dato", "davo"]},
                {"id": "c1pt7", "prompt": "Se ___ (noi - sapere) prima, ___ (organizzare) tutto meglio.", "answers": [["avessimo saputo"], ["avremmo organizzato"]], "explanation": "Third type, noi form.", "options": ["avessimo saputo", "sapevamo", "avremmo organizzato", "organizzavamo"]},
                {"id": "c1pt8", "prompt": "Se non ___ (lei - perdere) il treno, ___ (arrivare) in orario.", "answers": [["avesse perso"], ["sarebbe arrivata"]], "explanation": "Third type, essere in the main clause, agreeing with lei.", "options": ["avesse perso", "perdeva", "sarebbe arrivata", "arrivava"]},
                {"id": "c1pt9", "prompt": "Se ___ (voi - venire) alla festa, vi ___ (divertire) sicuramente.", "answers": [["foste venuti"], ["sareste divertiti"]], "explanation": "Third type, voi form.", "options": ["foste venuti", "venivate", "sareste divertiti", "divertivate"]},
                {"id": "c1pt10", "prompt": "Se ___ (io - accettare) quel lavoro, ora ___ (vivere) a Milano.", "answers": [["avessi accettato"], ["vivrei"]], "explanation": "Mixed hypothetical: past condition, present consequence.", "options": ["avessi accettato", "accettavo", "vivrei", "avrei vissuto"]},
                {"id": "c1pt11", "prompt": "Se ___ (tu - ascoltare) i miei consigli, non ___ (fare) quell'errore.", "answers": [["avessi ascoltato"], ["avresti fatto"]], "explanation": "Third type, both halves counterfactual.", "options": ["avessi ascoltato", "ascoltavi", "avresti fatto", "facevi"]},
             ]},
            {"id": "c1pt-mc2", "type": "multiple-choice", "title": "More Third-Type Choices",
             "items": [
                {"id": "c1pt12", "prompt": "Which mood/tense goes in the se-clause of the third type?", "options": ["congiuntivo trapassato", "condizionale passato", "congiuntivo imperfetto"], "answerIndex": 0, "explanation": "The se-clause always needs the congiuntivo trapassato in the third type."},
                {"id": "c1pt13", "prompt": "Which mood/tense goes in the main clause of the third type?", "options": ["condizionale passato", "congiuntivo trapassato", "futuro semplice"], "answerIndex": 0, "explanation": "The main clause needs the condizionale passato."},
                {"id": "c1pt14", "prompt": "\"Se avessi saputo, sarei venuto\" implies...", "options": ["I didn't know, and I didn't come.", "I knew, and I came.", "I will know and I will come."], "answerIndex": 0, "explanation": "The third type describes a counterfactual past."},
                {"id": "c1pt15", "prompt": "A mixed hypothetical pairs a past condition with which kind of consequence?", "options": ["a present consequence", "a past consequence", "a future consequence"], "answerIndex": 0, "explanation": "The consequence is felt now, so it uses the condizionale presente."},
                {"id": "c1pt16", "prompt": "Which sentence is a correct mixed hypothetical?", "options": ["Se avessi accettato quel lavoro, ora vivrei a Milano.", "Se accetterei quel lavoro, vivrei a Milano.", "Se ho accettato quel lavoro, vivo a Milano."], "answerIndex": 0, "explanation": "Past condition (congiuntivo trapassato) + present consequence (condizionale presente)."},
                {"id": "c1pt17", "prompt": "The third type describes a condition that is...", "options": ["counterfactual, in the past", "real and likely", "possible but unlikely, in the present"], "answerIndex": 0, "explanation": "The third type is specifically about the unreal past."},
                {"id": "c1pt18", "prompt": "Which is the correct condizionale passato of \"venire\", noi form?", "options": ["saremmo venuti", "avremmo venuto", "venivamo"], "answerIndex": 0, "explanation": "Venire takes essere, so the condizionale passato is saremmo venuti."},
                {"id": "c1pt19", "prompt": "\"Avrei accettato l'offerta se me l'avessero fatta prima\" — the order of clauses...", "options": ["can be flipped without changing meaning", "must stay se-clause first", "must stay main clause first"], "answerIndex": 0, "explanation": "The main clause and se-clause can appear in either order."},
             ]},
            {"id": "c1pt-tf", "type": "true-false", "title": "True or False?",
             "items": [
                {"id": "c1pt20", "statement": "The third type talks about a condition and consequence that both did not happen.", "answer": True, "explanation": "Both halves describe a counterfactual past."},
                {"id": "c1pt21", "statement": "The se-clause of the third type can use the conditional instead of the congiuntivo trapassato.", "answer": False, "explanation": "The se-clause always needs the congiuntivo trapassato, never the conditional."},
                {"id": "c1pt22", "statement": "A mixed hypothetical uses condizionale presente in the main clause for a present-day consequence.", "answer": True, "explanation": "This is exactly the mixed hypothetical pattern."},
                {"id": "c1pt23", "statement": "The third type is used for real, likely conditions.", "answer": False, "explanation": "That's the first type; the third type is for the unreal past."},
                {"id": "c1pt24", "statement": "Condizionale passato is built from avrei/sarei + past participle.", "answer": True, "explanation": "This is exactly how the condizionale passato is formed."},
                {"id": "c1pt25", "statement": "The se-clause and main clause can appear in either order without changing the meaning.", "answer": True, "explanation": "Word order between the two clauses is flexible."},
                {"id": "c1pt26", "statement": "The third type never mixes with a present consequence.", "answer": False, "explanation": "Mixed hypotheticals do exactly that, pairing a past condition with a present consequence."},
                {"id": "c1pt27", "statement": "\"Se avrei saputo\" is a correct way to start a third-type sentence.", "answer": False, "explanation": "The se-clause needs the congiuntivo trapassato, never the conditional."},
             ]},
        ],
        "summary": [
            "Third type (unreal past): se + congiuntivo trapassato, condizionale passato.",
            "Both halves are counterfactual: neither the condition nor its consequence actually happened.",
            "A mixed hypothetical pairs a past condition with a condizionale presente for a present consequence.",
        ],
    },
    {
        "id": "c1-gerundio-progressivo",
        "level": "C1", "unit": "1", "order": 3, "skill": "grammar", "strand": "gerund",
        "title": "Il Gerundio e la Forma Progressiva",
        "subtitle": "Stare + gerundio for actions in progress, and the gerund's other uses.",
        "objectives": [
            "Form the gerund of regular and common irregular verbs",
            "Use stare + gerundio for an action happening right now",
            "Use the gerund alone to express cause, means, or a simultaneous action",
        ],
        "content": {
            "intro": "The Italian gerund (-ando/-endo) is the base of the progressive form and, used on its own, a compact way to express cause, method, or a simultaneous action without a connector word.",
            "explanation": "<p>Regular gerunds: -are &rarr; -ando, -ere/-ire &rarr; -endo. A few verbs use their old Latin stem, matching the imperfetto: <em>fare &rarr; facendo, dire &rarr; dicendo, bere &rarr; bevendo</em>. Object and reflexive pronouns attach to the end of a standalone gerund, but go before <em>stare</em> in the progressive.</p>",
            "rules": [
                {"heading": "a) Stare + gerundio — progressive", "body": "<p>Marks an action genuinely in progress right now, more emphatic than the simple present: <em>Sto leggendo un libro.</em> (I am [right now] reading a book.) Pronouns go before stare or attach to the gerund: <em>Lo sto leggendo. / Sto leggendolo.</em></p>"},
                {"heading": "b) Gerund alone — cause, means, simultaneous action", "body": "<ul><li>Cause: <em>Studiando ogni giorno, ho imparato molto.</em> (By studying every day, I learned a lot.)</li><li>Simultaneous action: <em>Ho letto il giornale bevendo il caffè.</em> (I read the paper while drinking coffee.)</li></ul>"},
            ],
            "examples": [
                {"it": "Sto scrivendo un'email importante.", "en": "I'm [right now] writing an important email."},
                {"it": "Stavamo dormendo quando è arrivata la chiamata.", "en": "We were sleeping when the call came in."},
                {"it": "Camminando per la città, ho scoperto un bel caffè.", "en": "Walking through the city, I discovered a nice café."},
                {"it": "Ha imparato l'italiano guardando film senza sottotitoli.", "en": "He learned Italian by watching films without subtitles."},
            ],
            "commonMistakes": [
                {"wrong": "Sto leggere un libro.", "right": "Sto leggendo un libro.", "why": "Stare requires the gerund, not the infinitive, in the progressive form."},
                {"wrong": "Facendo attenzione. (spelled as if regular)", "right": "facendo (irregular stem fac-)", "why": "Fare's gerund uses the old stem fac-, matching its imperfetto (facevo), not a regular -are gerund."},
            ],
        },
        "exercises": [
            {"id": "c1gp-fill", "type": "fill-blank", "title": "Fill in the Blanks",
             "items": [
                {"id": "c1gp1", "prompt": "Cosa ___ (tu - fare)? Sto ___.", "answers": [["stai facendo"], ["studiando"]], "explanation": "Progressive: stare + gerundio.", "options": ["stai facendo", "fai", "studiando", "studiare"]},
                {"id": "c1gp2", "prompt": "___ (Bere) il caffè, ho letto le notizie.", "answers": [["Bevendo"]], "explanation": "Bere's irregular gerund stem: bevendo.", "options": ["Bevendo", "Berendo", "Bevuto"]},
             ]},
            {"id": "c1gp-mc", "type": "multiple-choice", "title": "Choose the Correct Form",
             "items": [
                {"id": "c1gp3", "prompt": "\"I learned a lot by traveling.\"", "options": ["Ho imparato molto viaggiare.", "Ho imparato molto viaggiando.", "Ho imparato molto viaggiato."], "answerIndex": 1, "explanation": "The gerund expresses means/method here."},
             ]},
            {"id": "c1gp-fill2", "type": "fill-blank", "title": "More Gerund Practice",
             "items": [
                {"id": "c1gp4", "prompt": "___ (Dire) la verità, mi sento meglio.", "answers": [["Dicendo"]], "explanation": "Dire's irregular gerund stem: dicendo.", "options": ["Dicendo", "Dicando", "Detto"]},
                {"id": "c1gp5", "prompt": "Loro ___ (stare - present) ___ (mangiare - gerund) quando ho chiamato.", "answers": [["stavano"], ["mangiando"]], "explanation": "Progressive in a past context.", "options": ["stavano", "stanno", "mangiando", "mangiare"]},
                {"id": "c1gp6", "prompt": "___ (Fare) attenzione, non ho fatto errori.", "answers": [["Facendo"]], "explanation": "Fare's irregular gerund stem: facendo.", "options": ["Facendo", "Farendo", "Fatto"]},
                {"id": "c1gp7", "prompt": "Sto ___ (leggere) un romanzo molto interessante.", "answers": [["leggendo"]], "explanation": "Regular -ere gerund: leggendo.", "options": ["leggendo", "leggere", "letto"]},
                {"id": "c1gp8", "prompt": "___ (Camminare) per il centro, ho incontrato un vecchio amico.", "answers": [["Camminando"]], "explanation": "Regular -are gerund: camminando.", "options": ["Camminando", "Camminendo", "Camminato"]},
                {"id": "c1gp9", "prompt": "Non sto ___ (scherzare), dico sul serio.", "answers": [["scherzando"]], "explanation": "Regular -are gerund: scherzando.", "options": ["scherzando", "scherzare", "scherzato"]},
                {"id": "c1gp10", "prompt": "___ (Uscire) di casa, ho dimenticato le chiavi.", "answers": [["Uscendo"]], "explanation": "Regular -ire gerund: uscendo.", "options": ["Uscendo", "Uscindo", "Uscito"]},
                {"id": "c1gp11", "prompt": "Stavo ___ (dormire) quando è suonato il telefono.", "answers": [["dormendo"]], "explanation": "Regular -ire gerund: dormendo.", "options": ["dormendo", "dormire", "dormito"]},
             ]},
            {"id": "c1gp-mc2", "type": "multiple-choice", "title": "More Gerund Choices",
             "items": [
                {"id": "c1gp12", "prompt": "Which is the gerund of \"fare\"?", "options": ["facendo", "farando", "fatto"], "answerIndex": 0, "explanation": "Fare's gerund is facendo, from the old stem fac-."},
                {"id": "c1gp13", "prompt": "Which is the gerund of \"dire\"?", "options": ["dicendo", "direndo", "detto"], "answerIndex": 0, "explanation": "Dire's gerund is dicendo, from the old stem dice-."},
                {"id": "c1gp14", "prompt": "\"Sto studiando\" emphasizes...", "options": ["an action happening right now", "a habitual action", "a future plan"], "answerIndex": 0, "explanation": "The progressive form emphasizes an action genuinely in progress."},
                {"id": "c1gp15", "prompt": "Where can pronouns go in the progressive form?", "options": ["before stare or attached to the gerund", "only attached to the gerund", "only before stare"], "answerIndex": 0, "explanation": "Both Lo sto leggendo and Sto leggendolo are correct."},
                {"id": "c1gp16", "prompt": "\"Ho imparato l'italiano guardando film\" — the gerund here expresses...", "options": ["means/method", "a command", "a question"], "answerIndex": 0, "explanation": "The standalone gerund expresses the method by which something was learned."},
                {"id": "c1gp17", "prompt": "Which is the correct gerund of \"bere\"?", "options": ["bevendo", "berendo", "bevuto"], "answerIndex": 0, "explanation": "Bere's gerund uses the old stem bev-: bevendo."},
                {"id": "c1gp18", "prompt": "A standalone gerund can express all of the following EXCEPT...", "options": ["a direct question", "cause", "a simultaneous action"], "answerIndex": 0, "explanation": "A gerund never forms a direct question."},
                {"id": "c1gp19", "prompt": "\"Sto leggendolo\" — where is the pronoun?", "options": ["attached to the gerund", "before stare", "after leggendo as a separate word"], "answerIndex": 0, "explanation": "Lo is attached directly to the end of leggendo."},
             ]},
            {"id": "c1gp-tf", "type": "true-false", "title": "True or False?",
             "items": [
                {"id": "c1gp20", "statement": "Regular -are verbs form their gerund with -ando.", "answer": True, "explanation": "Parlare → parlando follows this regular pattern."},
                {"id": "c1gp21", "statement": "Stare + infinito forms the Italian progressive.", "answer": False, "explanation": "The progressive is stare + gerundio, not the infinitive."},
                {"id": "c1gp22", "statement": "Fare's gerund is built from the irregular stem fac-, matching its imperfetto.", "answer": True, "explanation": "Facendo mirrors facevo, both from the old stem facere."},
                {"id": "c1gp23", "statement": "A gerund can express cause without needing a connector word.", "answer": True, "explanation": "Studiando ogni giorno, ho imparato molto expresses cause with no connector."},
                {"id": "c1gp24", "statement": "Pronouns always attach to stare, never to the gerund, in the progressive.", "answer": False, "explanation": "They can go before stare or attach to the gerund, both correct."},
                {"id": "c1gp25", "statement": "The progressive form is more emphatic than the simple present for an action happening right now.", "answer": True, "explanation": "Sto leggendo is more emphatic than the plain present leggo."},
                {"id": "c1gp26", "statement": "Dire's gerund is dicendo, based on the old stem dice-.", "answer": True, "explanation": "This is the correct irregular gerund of dire."},
                {"id": "c1gp27", "statement": "The gerund never combines with object or reflexive pronouns.", "answer": False, "explanation": "Pronouns attach to the end of a standalone gerund."},
             ]},
        ],
        "summary": [
            "Regular gerund: -are→-ando, -ere/-ire→-endo; some verbs use an irregular Latin-derived stem.",
            "Stare + gerundio marks an action genuinely in progress right now.",
            "A standalone gerund can express cause, method, or a simultaneous action, with pronouns attached to its end.",
        ],
    },
    {
        "id": "c1-connettivi-testuali",
        "level": "C1", "unit": "1", "order": 4, "skill": "writing", "strand": "discourse",
        "title": "Connettivi Testuali Avanzati",
        "subtitle": "Linking ideas like a fluent writer: contrast, cause, consequence, addition.",
        "objectives": [
            "Use a range of connectors beyond the basic e, ma, perché",
            "Choose connectors appropriate to formal written Italian",
            "Structure a short argumentative paragraph with clear logical connectors",
        ],
        "content": {
            "intro": "Fluent written Italian relies on a richer set of connectors than everyday speech — signalling contrast, consequence, and addition precisely instead of stringing ideas together with e and ma.",
            "explanation": "<p>These connectors are especially common in essays, articles, and formal writing/speech. Many pair naturally: <em>da un lato... dall'altro</em> (on one hand... on the other).</p>",
            "rules": [
                {"heading": "a) Contrast", "body": "<p><em>tuttavia, però, nonostante ciò, d'altra parte, al contrario, mentre</em> — all stronger/more formal alternatives to ma.</p>"},
                {"heading": "b) Cause and consequence", "body": "<p><em>poiché, dato che, dal momento che</em> (cause, more formal than perché); <em>quindi, perciò, di conseguenza, pertanto</em> (consequence, more formal than allora).</p>"},
                {"heading": "c) Addition and sequence", "body": "<p><em>inoltre, per di più, in aggiunta</em> (addition); <em>innanzitutto, in primo luogo, infine</em> (sequencing an argument).</p>"},
            ],
            "examples": [
                {"it": "Il progetto è ambizioso; tuttavia, i tempi sono realistici.", "en": "The project is ambitious; however, the timeline is realistic."},
                {"it": "Dato che il traffico era intenso, siamo arrivati in ritardo.", "en": "Since traffic was heavy, we arrived late."},
                {"it": "Il costo è aumentato; di conseguenza, abbiamo dovuto rivedere il budget.", "en": "The cost increased; as a result, we had to revise the budget."},
                {"it": "Da un lato capisco le tue ragioni; dall'altro, non sono d'accordo.", "en": "On one hand I understand your reasons; on the other, I don't agree."},
            ],
            "commonMistakes": [
                {"wrong": "Perciò using it to introduce a cause (instead of a consequence)", "right": "poiché/dato che for cause; perciò/quindi for consequence", "why": "Cause and consequence connectors aren't interchangeable — mixing them reverses the logical relationship of the sentence."},
                {"wrong": "Overusing tuttavia/quindi in casual conversation", "right": "però/allora in casual speech; tuttavia/quindi in writing", "why": "These heavier connectors read as formal/written register — using them constantly in casual speech can sound stilted."},
            ],
        },
        "exercises": [
            {"id": "c1ct2-fill", "type": "fill-blank", "title": "Fill in the Blanks",
             "items": [
                {"id": "c1ct2a", "prompt": "___ pioveva, siamo usciti lo stesso. (since/given that)", "answers": [["Dato che", "Poiché"]], "explanation": "Cause connector.", "options": ["Dato che", "Quindi", "Tuttavia"]},
                {"id": "c1ct2b", "prompt": "Ha lavorato molto; ___, ha ottenuto una promozione. (as a result)", "answers": [["di conseguenza", "quindi", "perciò"]], "explanation": "Consequence connector.", "options": ["di conseguenza", "poiché", "mentre"]},
             ]},
            {"id": "c1ct2-mc", "type": "multiple-choice", "title": "Choose the Right Connector",
             "items": [
                {"id": "c1ct2c", "prompt": "Which connector expresses contrast?", "options": ["inoltre", "tuttavia", "perciò"], "answerIndex": 1, "explanation": "Tuttavia (however) expresses contrast."},
             ]},
            {"id": "c1ctx-fill", "type": "fill-blank", "title": "More Connectors to Complete",
             "items": [
                {"id": "c1ctx1", "prompt": "Il progetto è rischioso; ___, potrebbe portare ottimi risultati. (however)", "answers": [["tuttavia", "però"]], "explanation": "Tuttavia/però express contrast.", "options": ["tuttavia", "quindi", "poiché"]},
                {"id": "c1ctx2", "prompt": "Le previsioni erano negative; ___, le vendite sono aumentate. (despite that)", "answers": [["nonostante ciò"]], "explanation": "Nonostante ciò is a fixed adverbial contrast connector.", "options": ["nonostante ciò", "quindi", "poiché"]},
                {"id": "c1ctx3", "prompt": "___ il traffico era intenso, siamo arrivati in ritardo. (since)", "answers": [["Dato che", "Poiché", "Dal momento che"]], "explanation": "These all introduce a formal cause.", "options": ["Dato che", "Quindi", "Tuttavia"]},
                {"id": "c1ctx4", "prompt": "Ha studiato molto; ___, ha superato l'esame con lode. (as a result)", "answers": [["di conseguenza", "quindi", "perciò", "pertanto"]], "explanation": "These all introduce a consequence.", "options": ["di conseguenza", "poiché", "mentre"]},
                {"id": "c1ctx5", "prompt": "___, vorrei ringraziare tutti i presenti. (first of all)", "answers": [["Innanzitutto", "In primo luogo"]], "explanation": "These sequence the first point of an argument.", "options": ["Innanzitutto", "Infine", "Inoltre"]},
                {"id": "c1ctx6", "prompt": "Il prodotto è di alta qualità; ___, il prezzo è competitivo. (moreover)", "answers": [["inoltre", "per di più", "in aggiunta"]], "explanation": "These express addition.", "options": ["inoltre", "mentre", "dato che"]},
                {"id": "c1ctx7", "prompt": "___, vorrei ringraziare il mio team per il duro lavoro. (finally/in closing)", "answers": [["Infine"]], "explanation": "Infine closes a sequence of points.", "options": ["Infine", "Innanzitutto", "Tuttavia"]},
                {"id": "c1ctx8", "prompt": "Il mercato cresce, ___ i costi rimangono stabili. (while/whereas)", "answers": [["mentre"]], "explanation": "Mentre expresses a contrast between simultaneous facts.", "options": ["mentre", "quindi", "perciò"]},
             ]},
            {"id": "c1ctx-mc", "type": "multiple-choice", "title": "More Connector Choices",
             "items": [
                {"id": "c1ctx9", "prompt": "Which connector expresses cause, more formal than perché?", "options": ["poiché", "tuttavia", "quindi"], "answerIndex": 0, "explanation": "Poiché is a formal cause connector."},
                {"id": "c1ctx10", "prompt": "Which connector expresses consequence?", "options": ["perciò", "poiché", "mentre"], "answerIndex": 0, "explanation": "Perciò expresses consequence, like quindi."},
                {"id": "c1ctx11", "prompt": "Which pair naturally goes together to contrast two sides of an argument?", "options": ["da un lato... dall'altro", "innanzitutto... infine", "poiché... quindi"], "answerIndex": 0, "explanation": "Da un lato...dall'altro contrasts two sides of an argument."},
                {"id": "c1ctx12", "prompt": "Which connector is used to sequence an argument's first point?", "options": ["innanzitutto", "tuttavia", "di conseguenza"], "answerIndex": 0, "explanation": "Innanzitutto introduces the first point."},
                {"id": "c1ctx13", "prompt": "Which connector would sound stilted in casual conversation?", "options": ["tuttavia", "ma", "e"], "answerIndex": 0, "explanation": "Tuttavia belongs mainly to formal/written register."},
                {"id": "c1ctx14", "prompt": "Which expresses addition?", "options": ["inoltre", "mentre", "poiché"], "answerIndex": 0, "explanation": "Inoltre (moreover) expresses addition."},
                {"id": "c1ctx15", "prompt": "Which is closest in meaning to \"perciò\"?", "options": ["quindi", "tuttavia", "mentre"], "answerIndex": 0, "explanation": "Quindi and perciò both express consequence."},
                {"id": "c1ctx16", "prompt": "\"Al contrario\" expresses...", "options": ["contrast", "cause", "addition"], "answerIndex": 0, "explanation": "Al contrario means \"on the contrary\", a contrast connector."},
             ]},
            {"id": "c1ctx-tf", "type": "true-false", "title": "True or False?",
             "items": [
                {"id": "c1ctx17", "statement": "Cause and consequence connectors are interchangeable in Italian.", "answer": False, "explanation": "They mark opposite logical directions and aren't interchangeable."},
                {"id": "c1ctx18", "statement": "Tuttavia is a more formal alternative to ma.", "answer": True, "explanation": "Tuttavia is the heavier, written-register equivalent of ma."},
                {"id": "c1ctx19", "statement": "Dato che and poiché can both introduce a cause.", "answer": True, "explanation": "Both are formal cause connectors."},
                {"id": "c1ctx20", "statement": "Quindi and perciò both express consequence.", "answer": True, "explanation": "Both mean \"therefore/as a result\"."},
                {"id": "c1ctx21", "statement": "Da un lato...dall'altro is used to sequence a list of points, not to contrast two sides.", "answer": False, "explanation": "It's specifically used to contrast two sides of an argument."},
                {"id": "c1ctx22", "statement": "Heavier written connectors like tuttavia and quindi are common in everyday casual speech.", "answer": False, "explanation": "They belong mainly to formal/written register."},
                {"id": "c1ctx23", "statement": "Innanzitutto is used to introduce the first point of an argument.", "answer": True, "explanation": "This is exactly its function."},
                {"id": "c1ctx24", "statement": "Mentre can express contrast between two simultaneous facts.", "answer": True, "explanation": "Mentre can mean both \"while\" and \"whereas\"."},
             ]},
        ],
        "summary": [
            "Formal connectors express cause (poiché, dato che), consequence (quindi, perciò), and contrast (tuttavia, d'altra parte) more precisely than e/ma/perché.",
            "Cause and consequence connectors are not interchangeable — they mark opposite logical directions.",
            "Heavier connectors belong mainly to written/formal register, not everyday conversation.",
        ],
    },
    {
        "id": "c1-registro-formale-informale",
        "level": "C1", "unit": "1", "order": 5, "skill": "writing", "strand": "register",
        "title": "Registro Formale e Informale nella Scrittura",
        "subtitle": "Choosing vocabulary and structure to match the situation.",
        "objectives": [
            "Identify markers of formal vs. informal written register",
            "Rewrite an informal sentence in a formal register and vice versa",
            "Use standard formal opening/closing formulas for emails and letters",
        ],
        "content": {
            "intro": "Beyond tu vs. Lei, Italian marks formality through vocabulary choice, sentence structure, and set phrases — especially visible in written communication.",
            "explanation": "<p>Formal writing favors longer, more explicit sentences, the connectors from the previous lesson, and a vocabulary that avoids colloquialisms. Informal writing (texts, casual emails to friends) allows contractions, colloquial vocabulary, and much shorter sentences.</p>",
            "rules": [
                {"heading": "a) Vocabulary pairs (informal → formal)", "body": "<p><em>un sacco di &rarr; molti/numerosi; un po' &rarr; un po' (fine) / leggermente; fare un giro &rarr; effettuare una visita; iniziare &rarr; dare inizio a; dire &rarr; comunicare, dichiarare</em></p>"},
                {"heading": "b) Email/letter formulas", "body": "<ul><li>Formal opening: <em>Gentile Sig.ra/Sig. [Cognome], La contatto per...</em></li><li>Formal closing: <em>Cordiali saluti / Distinti saluti</em></li><li>Informal opening: <em>Ciao [Nome],</em></li><li>Informal closing: <em>A presto! / Un abbraccio</em></li></ul>"},
            ],
            "examples": [
                {"it": "Gentile Dott.ssa Rossi, Le scrivo per chiederLe informazioni riguardo al Suo prossimo seminario.", "en": "Dear Dr. Rossi, I am writing to ask you for information about your upcoming seminar."},
                {"it": "Ciao Marco, ti scrivo per chiederti se sei libero sabato!", "en": "Hi Marco, I'm writing to ask if you're free Saturday!"},
                {"it": "La informiamo che la Sua richiesta è stata accolta.", "en": "We inform you that your request has been accepted."},
                {"it": "Ti volevo dire che ho accettato il lavoro!", "en": "I wanted to tell you I accepted the job!"},
            ],
            "commonMistakes": [
                {"wrong": "Ciao Direttore, volevo sapere... (mixing informal greeting with a formal context)", "right": "Gentile Direttore, vorrei sapere...", "why": "Mixing an informal opening with formal content and pronouns is inconsistent — pick one register and keep it throughout."},
                {"wrong": "Ending a formal email with Ciao!", "right": "Ending with Cordiali saluti / Distinti saluti", "why": "Ciao is strictly informal — a formal closing formula is expected to match a Lei-register email."},
            ],
        },
        "exercises": [
            {"id": "c1rf-mc", "type": "multiple-choice", "title": "Formal or Informal?",
             "items": [
                {"id": "c1rf1", "prompt": "Which closing fits a formal email to a company?", "options": ["A presto!", "Cordiali saluti", "Ciao ciao!"], "answerIndex": 1, "explanation": "Cordiali saluti is the standard formal closing."},
                {"id": "c1rf2", "prompt": "Which is the more formal way to say \"a lot of people\"?", "options": ["un sacco di gente", "numerose persone", "tanta gente"], "answerIndex": 1, "explanation": "Numerose persone is the formal-register equivalent."},
             ]},
            {"id": "c1rf-correction", "type": "correction", "title": "Fix the Register",
             "items": [
                {"id": "c1rf3", "incorrect": "Gentile Direttore, ciao! Volevo un po' di info.", "answer": ["Gentile Direttore, Le scrivo per richiedere alcune informazioni."], "explanation": "A formal opening (Gentile Direttore) should be followed by consistently formal vocabulary and structure, not casual expressions."},
             ]},
            {"id": "c1rf-fill2", "type": "fill-blank", "title": "More Register Practice",
             "items": [
                {"id": "c1rf4", "prompt": "___ Sig. Bianchi, Le scrivo per...", "answers": [["Gentile"]], "explanation": "Gentile is the standard formal opening.", "options": ["Gentile", "Ciao", "Ehi"]},
                {"id": "c1rf5", "prompt": "Un ___ di persone ha partecipato all'evento. (informal \"a lot of\")", "answers": [["sacco"]], "explanation": "Un sacco di is a colloquial, informal expression.", "options": ["sacco", "numero", "gruppo"]},
                {"id": "c1rf6", "prompt": "La ringrazio e Le porgo i miei ___ saluti. (formal closing word)", "answers": [["distinti", "cordiali"]], "explanation": "Distinti/cordiali saluti are standard formal closings.", "options": ["distinti", "cari", "tanti"]},
                {"id": "c1rf7", "prompt": "___, Anna! Come stai? (informal opening)", "answers": [["Ciao"]], "explanation": "Ciao is the standard informal opening.", "options": ["Ciao", "Gentile", "Egregio"]},
                {"id": "c1rf8", "prompt": "La informiamo che la Sua richiesta ___ (essere) stata accolta.", "answers": [["è"]], "explanation": "Formal passive, third person singular.", "options": ["è", "sei", "sono"]},
                {"id": "c1rf9", "prompt": "Ti volevo ___ (dire) che ho accettato il lavoro! (informal)", "answers": [["dire"]], "explanation": "Dire is the plain, informal verb; comunicare/dichiarare are the formal equivalents.", "options": ["dire", "comunicare", "dichiarare"]},
                {"id": "c1rf10", "prompt": "___ ringraziarLa per la disponibilità. (formal, \"I would like to\")", "answers": [["Vorrei"]], "explanation": "Vorrei is the polite, formal way to open a request.", "options": ["Vorrei", "Voglio", "Devo"]},
                {"id": "c1rf11", "prompt": "Un ___! (informal closing, \"a hug\")", "answers": [["abbraccio"]], "explanation": "Un abbraccio is a warm, informal closing.", "options": ["abbraccio", "saluto", "distinti saluti"]},
             ]},
            {"id": "c1rf-mc2", "type": "multiple-choice", "title": "More Register Choices",
             "items": [
                {"id": "c1rf12", "prompt": "Which is the formal equivalent of \"iniziare\"?", "options": ["dare inizio a", "cominciare", "partire"], "answerIndex": 0, "explanation": "Dare inizio a is the more formal, written equivalent."},
                {"id": "c1rf13", "prompt": "Which opening fits a formal letter to someone whose name you don't know?", "options": ["Egregio Signore", "Ciao", "Ehi"], "answerIndex": 0, "explanation": "Egregio Signore is a standard formal opening."},
                {"id": "c1rf14", "prompt": "Which is more informal: \"un po'\" or \"leggermente\"?", "options": ["un po'", "leggermente", "neither, they're equally formal"], "answerIndex": 0, "explanation": "Un po' is the everyday, informal choice; leggermente is more formal."},
                {"id": "c1rf15", "prompt": "Which verb is the formal equivalent of \"dire\"?", "options": ["comunicare", "parlare", "chiacchierare"], "answerIndex": 0, "explanation": "Comunicare/dichiarare are the formal equivalents of dire."},
                {"id": "c1rf16", "prompt": "What marks informal written Italian, besides vocabulary?", "options": ["contractions and short sentences", "longer, explicit sentences", "exclusively formulaic phrases"], "answerIndex": 0, "explanation": "Informal writing favors contractions and shorter sentences."},
                {"id": "c1rf17", "prompt": "Which closing would be inconsistent in a formal email?", "options": ["Ciao ciao!", "Cordiali saluti", "Distinti saluti"], "answerIndex": 0, "explanation": "Ciao ciao is strictly informal, inconsistent with a formal email."},
                {"id": "c1rf18", "prompt": "\"Effettuare una visita\" is the formal equivalent of...", "options": ["fare un giro", "fare colazione", "fare finta"], "answerIndex": 0, "explanation": "Effettuare una visita is the formal register version of fare un giro."},
                {"id": "c1rf19", "prompt": "What should you do if you start an email formally?", "options": ["keep the whole email formal, consistently", "mix in informal phrases for warmth", "switch to informal for the closing"], "answerIndex": 0, "explanation": "Consistency of register matters more than any single word."},
             ]},
            {"id": "c1rf-tf", "type": "true-false", "title": "True or False?",
             "items": [
                {"id": "c1rf20", "statement": "Formal register avoids colloquial vocabulary.", "answer": True, "explanation": "Formal writing favors precise, non-colloquial vocabulary."},
                {"id": "c1rf21", "statement": "Tu and Lei are the only markers of formality in Italian.", "answer": False, "explanation": "Vocabulary, sentence structure, and set phrases also mark formality."},
                {"id": "c1rf22", "statement": "Cordiali saluti is an appropriate closing for a casual text to a friend.", "answer": False, "explanation": "It's a formal closing, inconsistent with a casual text."},
                {"id": "c1rf23", "statement": "Contractions and colloquial vocabulary are typical of informal writing.", "answer": True, "explanation": "These are hallmarks of informal register."},
                {"id": "c1rf24", "statement": "Mixing a formal opening with informal vocabulary throughout is considered good style.", "answer": False, "explanation": "Consistency of register matters — mixing them is inconsistent."},
                {"id": "c1rf25", "statement": "\"Numerose persone\" is more formal than \"un sacco di gente\".", "answer": True, "explanation": "Numerose persone is the formal-register equivalent."},
                {"id": "c1rf26", "statement": "Formal writing tends to use shorter, more fragmented sentences than informal writing.", "answer": False, "explanation": "Formal writing tends toward longer, more explicit sentences."},
                {"id": "c1rf27", "statement": "Set opening/closing formulas exist for both formal and informal correspondence.", "answer": True, "explanation": "Both registers have their own standard formulas."},
             ]},
        ],
        "summary": [
            "Formal register favors explicit, longer sentences and formal vocabulary; informal favors contractions and colloquialisms.",
            "Set formulas exist for opening/closing formal and informal correspondence — don't mix them.",
            "Consistency matters more than any single word choice: pick a register and hold it throughout.",
        ],
    },
    {
        "id": "c1-verbi-pronominali",
        "level": "C1", "unit": "1", "order": 6, "skill": "grammar", "strand": "pronominal-verbs",
        "title": "Verbi Pronominali",
        "subtitle": "Farsi, andarsene, cavarsela — idiomatic verbs built from pronoun combinations.",
        "objectives": [
            "Recognize pronominal verbs as fixed idiomatic units",
            "Conjugate andarsene and cavarsela correctly across their pronoun set",
            "Use common pronominal verbs naturally in context",
        ],
        "content": {
            "intro": "Pronominal verbs fuse a base verb with one or more pronouns into an idiomatic unit whose meaning often can't be guessed from the parts — a hallmark of fluent, native-sounding Italian.",
            "explanation": "<p><strong>Andarsene</strong> (to leave, to go away) combines the reflexive andarsi with ne, both of which move together through the conjugation. <strong>Cavarsela</strong> (to get by, to manage) combines cavarsi with la. These aren't literal reflexive/partitive meanings anymore — they're memorized as whole idiomatic verbs.</p>",
            "table": "<div class=\"table-scroll\"><table class=\"ref-table\"><caption>Andarsene — present tense</caption><thead><tr><th>Subject</th><th>Form</th></tr></thead><tbody><tr><td>io</td><td>me ne vado</td></tr><tr><td>tu</td><td>te ne vai</td></tr><tr><td>lui/lei</td><td>se ne va</td></tr><tr><td>noi</td><td>ce ne andiamo</td></tr><tr><td>voi</td><td>ve ne andate</td></tr><tr><td>loro</td><td>se ne vanno</td></tr></tbody></table></div>",
            "rules": [
                {"heading": "a) Common pronominal verbs", "body": "<ul><li><em>farcela</em> — to manage, to make it: <em>Ce l'ho fatta!</em> (I made it!)</li><li><em>cavarsela</em> — to get by: <em>Me la cavo bene in inglese.</em> (I get by well in English.)</li><li><em>prendersela</em> — to take offense/get upset: <em>Non prendertela!</em> (Don't take it personally!)</li><li><em>sentirsela</em> — to feel up to something: <em>Non me la sento di uscire stasera.</em></li></ul>"},
                {"heading": "b) Passato prossimo of andarsene", "body": "<p>Takes essere, with the participle agreeing: <em>Se n'è andato.</em> (He left.) <em>Se ne sono andate.</em> (They [f.] left.)</p>"},
            ],
            "examples": [
                {"it": "Me ne vado, ci vediamo domani.", "en": "I'm leaving, see you tomorrow."},
                {"it": "Non ce la faccio più.", "en": "I can't take it anymore."},
                {"it": "Se l'è cavata benissimo all'esame.", "en": "He/she got through the exam really well."},
                {"it": "Non prendertela, non era colpa tua.", "en": "Don't take it personally, it wasn't your fault."},
            ],
            "commonMistakes": [
                {"wrong": "Io vado ne.", "right": "Me ne vado.", "why": "Andarsene's pronouns (me/te/se/ce/ve/se + ne) precede the verb as a fixed unit — they can't be reordered or split."},
                {"wrong": "Ho fatta cela. (word order)", "right": "Ce l'ho fatta.", "why": "The combined pronoun ce l' comes before the auxiliary, as one fixed sequence."},
            ],
        },
        "exercises": [
            {"id": "c1vp-fill", "type": "fill-blank", "title": "Fill in the Blanks",
             "items": [
                {"id": "c1vp1", "prompt": "Sono stanco, ___ vado a dormire. (andarsene, io)", "answers": [["me ne"]], "explanation": "Io form of andarsene: me ne vado.", "options": ["me ne", "mi ne", "ne mi"]},
                {"id": "c1vp2", "prompt": "Finalmente ___ fatta! (farcela, io, passato prossimo)", "answers": [["ce l'ho"]], "explanation": "Ce l'ho fatta — I made it.", "options": ["ce l'ho", "l'ho ce", "ce ho la"]},
             ]},
            {"id": "c1vp-mc", "type": "multiple-choice", "title": "Choose the Correct Meaning",
             "items": [
                {"id": "c1vp3", "prompt": "\"Non prendertela\" means...", "options": ["Don't take it (an object) with you.", "Don't take offense / don't be upset about it.", "Don't take it away from him."], "answerIndex": 1, "explanation": "Prendersela is an idiomatic pronominal verb meaning to take offense/get upset."},
             ]},
            {"id": "c1vp-fill2", "type": "fill-blank", "title": "More Pronominal Verb Practice",
             "items": [
                {"id": "c1vp4", "prompt": "___ vai, io resto qui. (andarsene, tu)", "answers": [["Te ne"]], "explanation": "Tu form of andarsene: te ne vai.", "options": ["Te ne", "Ti ne", "Ne te"]},
                {"id": "c1vp5", "prompt": "Lei ___ va senza salutare. (andarsene, lei)", "answers": [["se ne"]], "explanation": "Lei form of andarsene: se ne va.", "options": ["se ne", "si ne", "ne se"]},
                {"id": "c1vp6", "prompt": "Non ___ sento di parlarne ora. (sentirsela, io)", "answers": [["me la"]], "explanation": "Io form of sentirsela: me la sento.", "options": ["me la", "mi la", "la me"]},
                {"id": "c1vp7", "prompt": "___ caviamo bene in situazioni difficili. (cavarsela, noi)", "answers": [["ce la"]], "explanation": "Noi form of cavarsela: ce la caviamo.", "options": ["ce la", "ci la", "la ci"]},
                {"id": "c1vp8", "prompt": "Non ___ prendere, era solo uno scherzo! (prendersela, tu, negative imperative)", "answers": [["te la"]], "explanation": "Tu form of prendersela: te la prendi / non te la prendere.", "options": ["te la", "ti la", "la ti"]},
                {"id": "c1vp9", "prompt": "Finalmente ce l'___ (fare - passato prossimo, loro)", "answers": [["hanno fatta"]], "explanation": "Farcela, loro passato prossimo: ce l'hanno fatta.", "options": ["hanno fatta", "sono fatta", "hanno fatto"]},
                {"id": "c1vp10", "prompt": "___ vado, a domani! (andarsene, io)", "answers": [["Me ne"]], "explanation": "Io form of andarsene: me ne vado.", "options": ["Me ne", "Mi ne", "Ne mi"]},
             ]},
            {"id": "c1vp-mc2", "type": "multiple-choice", "title": "More Pronominal Verb Choices",
             "items": [
                {"id": "c1vp11", "prompt": "\"Se n'è andato\" means...", "options": ["He left.", "He is going.", "He will leave."], "answerIndex": 0, "explanation": "Se n'è andato is the passato prossimo of andarsene."},
                {"id": "c1vp12", "prompt": "Which pronominal verb means \"to manage/get by\"?", "options": ["cavarsela", "andarsene", "sentirsela"], "answerIndex": 0, "explanation": "Cavarsela means to manage/get by."},
                {"id": "c1vp13", "prompt": "Which pronominal verb means \"to take offense/get upset\"?", "options": ["prendersela", "farcela", "cavarsela"], "answerIndex": 0, "explanation": "Prendersela is the idiomatic verb for taking offense."},
                {"id": "c1vp14", "prompt": "\"Ce l'ho fatta!\" means...", "options": ["I made it!", "I have it!", "I did it to her!"], "answerIndex": 0, "explanation": "Farcela means to manage/make it."},
                {"id": "c1vp15", "prompt": "Which auxiliary does andarsene take in the passato prossimo?", "options": ["essere", "avere", "either, freely"], "answerIndex": 0, "explanation": "Andarsene always takes essere."},
                {"id": "c1vp16", "prompt": "\"Non me la sento di uscire stasera\" means...", "options": ["I don't feel up to going out tonight.", "I don't feel it in my hand tonight.", "I won't go out with her tonight."], "answerIndex": 0, "explanation": "Sentirsela means to feel up to doing something."},
                {"id": "c1vp17", "prompt": "Pronominal verbs are best understood as...", "options": ["fixed idiomatic units, not literal reflexive+pronoun combos", "fully literal reflexive verbs", "random combinations with no fixed meaning"], "answerIndex": 0, "explanation": "Their meaning often can't be guessed from the individual parts."},
             ]},
            {"id": "c1vp-tf", "type": "true-false", "title": "True or False?",
             "items": [
                {"id": "c1vp18", "statement": "Andarsene's pronouns can be reordered freely.", "answer": False, "explanation": "They form a fixed sequence (me/te/se/ce/ve/se + ne)."},
                {"id": "c1vp19", "statement": "Farcela means \"to manage/make it\".", "answer": True, "explanation": "This is farcela's idiomatic meaning."},
                {"id": "c1vp20", "statement": "Cavarsela combines cavarsi with the pronoun la.", "answer": True, "explanation": "Cavarsela = cavarsi + la, fused into one idiomatic verb."},
                {"id": "c1vp21", "statement": "The participle in andarsene's passato prossimo agrees with the subject.", "answer": True, "explanation": "Se n'è andata shows normal essere-participle agreement."},
                {"id": "c1vp22", "statement": "Prendersela is used literally to mean \"to take something with you\".", "answer": False, "explanation": "It's idiomatic for taking offense/getting upset, not literal."},
                {"id": "c1vp23", "statement": "Pronominal verbs are a hallmark of fluent, native-sounding Italian.", "answer": True, "explanation": "They're a genuine marker of advanced fluency."},
                {"id": "c1vp24", "statement": "Sentirsela means \"to feel up to doing something\".", "answer": True, "explanation": "This is exactly its idiomatic meaning."},
             ]},
        ],
        "summary": [
            "Pronominal verbs (andarsene, cavarsela, farcela, prendersela) are idiomatic fixed units, not literal reflexive+pronoun combinations.",
            "Their pronoun sequence moves together as a block through the conjugation.",
            "Andarsene takes essere in the passato prossimo, with normal participle agreement.",
        ],
    },
    {
        "id": "c1-sfumature-congiuntivo",
        "level": "C1", "unit": "1", "order": 7, "skill": "grammar", "strand": "subjunctive",
        "title": "Sfumature del Congiuntivo",
        "subtitle": "The independent subjunctive: wishes, doubts, and concession without che.",
        "objectives": [
            "Use the subjunctive independently to express a wish (magari, che)",
            "Use the subjunctive in concessive clauses (benché, sebbene, nonostante)",
            "Recognize the doubt-expressing subjunctive in a standalone question",
        ],
        "content": {
            "intro": "Beyond che-clauses, the subjunctive appears on its own to express wishes, doubts, and concession — small, idiomatic patterns that make speech sound genuinely fluent rather than textbook-correct.",
            "explanation": "<p>An independent subjunctive can open a sentence with an implied \"I wish\" (<em>Magari piovesse!</em>, If only it would rain!) or ask a rhetorical, doubtful question (<em>Che sia già partito?</em>, Could he have already left?). Concessive conjunctions (although/even though) also trigger the subjunctive, unlike their English equivalents.</p>",
            "rules": [
                {"heading": "a) Wishes", "body": "<p><em>Magari</em> + congiuntivo (imperfetto for something unlikely/impossible, trapassato for the past): <em>Magari avessi più tempo!</em> (If only I had more time!) <em>Che Dio ce la mandi buona.</em> (a set expression, \"let's hope for the best\")</p>"},
                {"heading": "b) Concession", "body": "<p><em>benché, sebbene, nonostante, malgrado</em> + congiuntivo: <em>Benché piova, usciamo lo stesso.</em> (Although it's raining, we're going out anyway.)</p>"},
                {"heading": "c) Doubtful questions", "body": "<p><em>Che + congiuntivo</em> as a standalone rhetorical question: <em>Che si sia dimenticato?</em> (Could he have forgotten?)</p>"},
            ],
            "examples": [
                {"it": "Magari fosse così semplice!", "en": "If only it were that simple!"},
                {"it": "Sebbene sia stanco, continuo a lavorare.", "en": "Although I'm tired, I keep working."},
                {"it": "Nonostante avessero poco tempo, hanno finito il progetto.", "en": "Despite having little time, they finished the project."},
                {"it": "Che abbia frainteso?", "en": "Could he/she have misunderstood?"},
            ],
            "commonMistakes": [
                {"wrong": "Benché piove, usciamo lo stesso.", "right": "Benché piova, usciamo lo stesso.", "why": "Concessive conjunctions like benché always trigger the subjunctive in Italian, unlike English \"although\", which takes a normal indicative."},
                {"wrong": "Magari ho più tempo!", "right": "Magari avessi più tempo!", "why": "An unreal/unlikely wish with magari needs the congiuntivo imperfetto, not the indicative."},
            ],
        },
        "exercises": [
            {"id": "c1sc-fill", "type": "fill-blank", "title": "Fill in the Blanks",
             "items": [
                {"id": "c1sc1", "prompt": "Sebbene ___ (essere) difficile, ce l'ho fatta.", "answers": [["fosse"]], "explanation": "Sebbene always triggers the subjunctive.", "options": ["fosse", "era", "è stato"]},
                {"id": "c1sc2", "prompt": "Magari ___ (io - potere) venire con te!", "answers": [["potessi"]], "explanation": "Unreal wish with magari → congiuntivo imperfetto.", "options": ["potessi", "posso", "potrei"]},
             ]},
            {"id": "c1sc-mc", "type": "multiple-choice", "title": "Choose the Correct Form",
             "items": [
                {"id": "c1sc3", "prompt": "\"Despite the rain, we went out.\"", "options": ["Nonostante piovesse, siamo usciti.", "Nonostante pioveva, siamo usciti.", "Nonostante piove, siamo usciti."], "answerIndex": 0, "explanation": "Nonostante triggers the subjunctive."},
             ]},
            {"id": "c1sc-fill2", "type": "fill-blank", "title": "More Independent Subjunctive Practice",
             "items": [
                {"id": "c1sc4", "prompt": "Nonostante ___ (loro - avere) poco tempo, hanno finito il progetto.", "answers": [["avessero"]], "explanation": "Nonostante triggers the subjunctive.", "options": ["avessero", "avevano", "hanno avuto"]},
                {"id": "c1sc5", "prompt": "Magari ___ (io - potere) tornare indietro nel tempo!", "answers": [["potessi"]], "explanation": "Unreal wish with magari → congiuntivo imperfetto.", "options": ["potessi", "posso", "potrei"]},
                {"id": "c1sc6", "prompt": "Malgrado ___ (essere) tardi, siamo usciti lo stesso.", "answers": [["fosse"]], "explanation": "Malgrado triggers the subjunctive, like benché/sebbene/nonostante.", "options": ["fosse", "era", "è stato"]},
                {"id": "c1sc7", "prompt": "Che ___ (lui - dimenticare) l'appuntamento?", "answers": [["abbia dimenticato"]], "explanation": "A doubtful rhetorical question opened with che + congiuntivo.", "options": ["abbia dimenticato", "ha dimenticato", "dimenticava"]},
                {"id": "c1sc8", "prompt": "Benché ___ (piovere), la partita continua.", "answers": [["piova"]], "explanation": "Benché triggers the subjunctive.", "options": ["piova", "piove", "pioveva"]},
                {"id": "c1sc9", "prompt": "Magari ___ (essere) tutto più semplice!", "answers": [["fosse"]], "explanation": "Unreal wish with magari → congiuntivo imperfetto.", "options": ["fosse", "è", "sarebbe"]},
                {"id": "c1sc10", "prompt": "Sebbene ___ (io - studiare) molto, non ho superato l'esame.", "answers": [["abbia studiato"]], "explanation": "Sebbene triggers the subjunctive.", "options": ["abbia studiato", "ho studiato", "studiavo"]},
             ]},
            {"id": "c1sc-mc2", "type": "multiple-choice", "title": "More Independent Subjunctive Choices",
             "items": [
                {"id": "c1sc11", "prompt": "Which conjunction always triggers the subjunctive, unlike English \"although\"?", "options": ["benché", "perché", "mentre"], "answerIndex": 0, "explanation": "Benché is a concessive conjunction that always takes the subjunctive."},
                {"id": "c1sc12", "prompt": "\"Magari fosse così semplice!\" expresses...", "options": ["an unreal wish", "a real fact", "a doubtful question"], "answerIndex": 0, "explanation": "Magari + congiuntivo imperfetto expresses an unreal wish."},
                {"id": "c1sc13", "prompt": "\"Che si sia dimenticato?\" is an example of...", "options": ["a doubtful, rhetorical question", "a certain statement", "a command"], "answerIndex": 0, "explanation": "Che + congiuntivo opens a doubtful, rhetorical question."},
                {"id": "c1sc14", "prompt": "Which of these is NOT a concessive conjunction?", "options": ["quindi", "sebbene", "nonostante"], "answerIndex": 0, "explanation": "Quindi expresses consequence, not concession."},
                {"id": "c1sc15", "prompt": "Magari + congiuntivo trapassato expresses a wish about...", "options": ["the past", "the present", "the future"], "answerIndex": 0, "explanation": "The trapassato form is used for wishes about the past."},
                {"id": "c1sc16", "prompt": "Which sentence correctly uses a concessive conjunction?", "options": ["Benché piova, usciamo lo stesso.", "Benché piove, usciamo lo stesso.", "Benché pioverà, usciamo lo stesso."], "answerIndex": 0, "explanation": "Benché requires the subjunctive, piova."},
                {"id": "c1sc17", "prompt": "An independent subjunctive can express all of the following EXCEPT...", "options": ["a certain, established fact", "a wish", "a doubtful question"], "answerIndex": 0, "explanation": "A certain fact takes the indicative, not the subjunctive."},
             ]},
            {"id": "c1sc-tf", "type": "true-false", "title": "True or False?",
             "items": [
                {"id": "c1sc18", "statement": "Benché, sebbene, nonostante and malgrado all trigger the subjunctive.", "answer": True, "explanation": "All four are concessive conjunctions requiring the subjunctive."},
                {"id": "c1sc19", "statement": "Magari is only used with the congiuntivo presente.", "answer": False, "explanation": "It pairs with the imperfetto (unlikely/impossible) or trapassato (past), not the presente."},
                {"id": "c1sc20", "statement": "A doubtful rhetorical question can open with che + congiuntivo.", "answer": True, "explanation": "Che si sia dimenticato? is exactly this pattern."},
                {"id": "c1sc21", "statement": "Concessive clauses in English also require a special mood, just like Italian.", "answer": False, "explanation": "English \"although\" takes the normal indicative, unlike Italian's subjunctive-triggering conjunctions."},
                {"id": "c1sc22", "statement": "Nonostante avessero poco tempo uses the congiuntivo trapassato because it refers to an earlier, completed state.", "answer": True, "explanation": "The trapassato marks a completed state before the main clause."},
                {"id": "c1sc23", "statement": "These independent subjunctive uses are typical of textbook-only, unnatural Italian.", "answer": False, "explanation": "They mark genuinely fluent, natural speech."},
                {"id": "c1sc24", "statement": "Sebbene and benché are interchangeable, both meaning \"although\".", "answer": True, "explanation": "Both are concessive conjunctions with the same meaning."},
             ]},
        ],
        "summary": [
            "Magari + congiuntivo expresses an unreal wish; che + congiuntivo can open a doubtful, rhetorical question.",
            "Concessive conjunctions (benché, sebbene, nonostante, malgrado) always trigger the subjunctive, unlike English \"although\".",
            "These independent uses go beyond che-clause triggers and mark genuinely fluent speech.",
        ],
    },
    {
        "id": "c1-ci-ne-avanzato",
        "level": "C1", "unit": "1", "order": 8, "skill": "grammar", "strand": "pronouns",
        "title": "Ci e Ne Avanzati con l'Imperativo e l'Infinito",
        "subtitle": "Combining pronouns, ci and ne with commands and infinitives, including irregular tu forms.",
        "objectives": [
            "Attach ci, ne, and combined pronouns correctly to the informal imperative",
            "Apply consonant doubling with the irregular tu imperatives (va', da', fa', sta', di')",
            "Combine multiple pronouns with an infinitive after another verb",
        ],
        "content": {
            "intro": "At this level, pronoun attachment needs to work smoothly even in the trickiest combinations: an irregular tu imperative plus a pronoun, or a chain of pronouns onto an infinitive after a modal verb.",
            "explanation": "<p>The apostrophized irregular tu imperatives (va', da', fa', sta', di') <strong>double the first consonant</strong> of any pronoun that attaches to them (except gli): <em>va' + ci &rarr; vacci; da' + mi &rarr; dammi; fa' + lo &rarr; fallo; di' + gli &rarr; digli</em> (gli never doubles). With a modal + infinitive, pronouns (including combined ones, ci, ne) can attach to the infinitive or precede the modal — both correct, but the attached form is more common in formal writing.</p>",
            "rules": [
                {"heading": "a) Consonant doubling after va'/da'/fa'/sta'/di'", "body": "<ul><li><em>Vacci subito!</em> (Go there right away!)</li><li><em>Dammi una mano.</em> (Give me a hand.)</li><li><em>Fallo per me.</em> (Do it for me.)</li><li><em>Digli la verità.</em> (Tell him the truth — gli never doubles.)</li></ul>"},
                {"heading": "b) Pronouns with modal + infinitive", "body": "<p><em>Voglio andarci.</em> / <em>Ci voglio andare.</em> <em>Devo dirglielo.</em> / <em>Glielo devo dire.</em> (combined pronoun, both positions correct)</p>"},
            ],
            "examples": [
                {"it": "Vacci tu, io sono troppo stanco.", "en": "You go there, I'm too tired."},
                {"it": "Dammi il tuo numero, ti chiamo dopo.", "en": "Give me your number, I'll call you later."},
                {"it": "Fallo subito, non aspettare.", "en": "Do it right away, don't wait."},
                {"it": "Devo dirglielo prima che sia troppo tardi.", "en": "I have to tell him/her before it's too late."},
                {"it": "Non voglio più parlarne.", "en": "I don't want to talk about it anymore."},
            ],
            "commonMistakes": [
                {"wrong": "Vaci subito!", "right": "Vacci subito!", "why": "The pronoun's first consonant doubles after va'/da'/fa'/sta' — a single c would be a spelling error here."},
                {"wrong": "Digli la verità → Dilli la verità", "right": "Digli la verità (no doubling)", "why": "Gli is the one pronoun that never doubles after these irregular imperatives — a genuine, memorized exception."},
            ],
        },
        "exercises": [
            {"id": "c1cn-fill", "type": "fill-blank", "title": "Fill in the Blanks",
             "items": [
                {"id": "c1cn1", "prompt": "___ subito! (Vai lì — irregular tu imperative + ci)", "answers": [["Vacci"]], "explanation": "Va' + ci, with consonant doubling: vacci.", "options": ["Vacci", "Vaci", "Va'ci"]},
                {"id": "c1cn2", "prompt": "___ una mano, per favore! (Dai a me — irregular tu imperative + mi)", "answers": [["Dammi"]], "explanation": "Da' + mi, with doubling: dammi.", "options": ["Dammi", "Dami", "Da'mi"]},
             ]},
            {"id": "c1cn-mc", "type": "multiple-choice", "title": "Choose the Correct Form",
             "items": [
                {"id": "c1cn3", "prompt": "\"Tell him!\" (Digli, or the wrong doubled version?)", "options": ["Dilli!", "Digli!", "Diglli!"], "answerIndex": 1, "explanation": "Gli never doubles after these irregular imperatives."},
             ]},
            {"id": "c1cn-fill2", "type": "fill-blank", "title": "More Ci/Ne with Commands Practice",
             "items": [
                {"id": "c1cn4", "prompt": "___! (Sta' lì — irregular tu imperative + ci, \"stay there\")", "answers": [["Stacci"]], "explanation": "Sta' + ci, with doubling: stacci.", "options": ["Stacci", "Staci", "Sta'ci"]},
                {"id": "c1cn5", "prompt": "___ la verità! (Di' a lui — irregular tu imperative + gli, no doubling)", "answers": [["Digli"]], "explanation": "Gli never doubles: digli.", "options": ["Digli", "Dilli", "Digl'i"]},
                {"id": "c1cn6", "prompt": "___! (Fai questo per me — irregular tu imperative + lo)", "answers": [["Fallo"]], "explanation": "Fa' + lo, with doubling: fallo.", "options": ["Fallo", "Falo", "Fa'lo"]},
                {"id": "c1cn7", "prompt": "Non voglio più ___. (parlarne — pronoun attached to infinitive)", "answers": [["parlarne"]], "explanation": "Ne attaches to the end of the infinitive.", "options": ["parlarne", "ne parlare", "parlare ne"]},
                {"id": "c1cn8", "prompt": "Devo ___. (dirglielo — combined pronoun attached to infinitive)", "answers": [["dirglielo"]], "explanation": "Glielo attaches to the end of the infinitive.", "options": ["dirglielo", "glielo dire", "dire glielo"]},
                {"id": "c1cn9", "prompt": "___ tu, io sono troppo stanco. (Vacci, irregular tu imperative + ci)", "answers": [["Vacci"]], "explanation": "Va' + ci, with doubling: vacci.", "options": ["Vacci", "Vaci", "Va'ci"]},
                {"id": "c1cn10", "prompt": "___ il tuo numero! (Dammi — irregular tu imperative + mi)", "answers": [["Dammi"]], "explanation": "Da' + mi, with doubling: dammi.", "options": ["Dammi", "Dami", "Da'mi"]},
                {"id": "c1cn11", "prompt": "Non ___ parlare più. (ne + voglio, pronoun before the modal)", "answers": [["ne voglio"]], "explanation": "Ne can precede the modal instead of attaching to the infinitive.", "options": ["ne voglio", "voglio ne", "ne vogliono"]},
             ]},
            {"id": "c1cn-mc2", "type": "multiple-choice", "title": "More Command and Pronoun Choices",
             "items": [
                {"id": "c1cn12", "prompt": "Which pronoun never doubles after va'/da'/fa'/sta'/di'?", "options": ["gli", "lo", "ci"], "answerIndex": 0, "explanation": "Gli is the one memorized exception."},
                {"id": "c1cn13", "prompt": "Which is the correct doubled form of \"fa' + lo\"?", "options": ["fallo", "falo", "fa'lo"], "answerIndex": 0, "explanation": "The first consonant of lo doubles: fallo."},
                {"id": "c1cn14", "prompt": "With a modal + infinitive, where can pronouns go?", "options": ["attach to the infinitive or precede the modal", "only attach to the infinitive", "only precede the modal"], "answerIndex": 0, "explanation": "Both positions are correct."},
                {"id": "c1cn15", "prompt": "Which is the correct doubled form of \"da' + mi\"?", "options": ["dammi", "dami", "da'mi"], "answerIndex": 0, "explanation": "The first consonant of mi doubles: dammi."},
                {"id": "c1cn16", "prompt": "\"Devo dirglielo\" and \"Glielo devo dire\" are...", "options": ["both correct, same meaning", "only the first correct", "only the second correct"], "answerIndex": 0, "explanation": "Both pronoun positions are equally correct."},
                {"id": "c1cn17", "prompt": "Which is the correct doubled form of \"va' + ci\"?", "options": ["vacci", "vaci", "va'ci"], "answerIndex": 0, "explanation": "The first consonant of ci doubles: vacci."},
                {"id": "c1cn18", "prompt": "\"Non voglio più parlarne\" means...", "options": ["I don't want to talk about it anymore.", "I don't want to talk to her anymore.", "I don't want to talk at all."], "answerIndex": 0, "explanation": "Ne here replaces a topic already mentioned."},
                {"id": "c1cn19", "prompt": "Which irregular tu imperatives cause consonant doubling?", "options": ["va', da', fa', sta', di'", "vai, dai, fai, stai, dici", "andare, dare, fare, stare, dire"], "answerIndex": 0, "explanation": "These are the apostrophized short forms that trigger doubling."},
             ]},
            {"id": "c1cn-tf", "type": "true-false", "title": "True or False?",
             "items": [
                {"id": "c1cn20", "statement": "Gli is the one pronoun that never doubles after the apostrophized irregular tu imperatives.", "answer": True, "explanation": "This is a memorized exception."},
                {"id": "c1cn21", "statement": "Vaci is the correct spelling of va' + ci.", "answer": False, "explanation": "The correct doubled spelling is vacci."},
                {"id": "c1cn22", "statement": "Pronouns can only attach to the infinitive after a modal verb, never precede it.", "answer": False, "explanation": "Both positions are correct."},
                {"id": "c1cn23", "statement": "Digli means \"tell him\" and never doubles the gli.", "answer": True, "explanation": "Gli is the exception to the doubling rule."},
                {"id": "c1cn24", "statement": "Fallo means \"do it\", from fa' + lo with doubling.", "answer": True, "explanation": "This is exactly how fallo is formed."},
                {"id": "c1cn25", "statement": "These fine points of pronoun placement mark fluent, C1-level control.", "answer": True, "explanation": "Mastering these details is a genuine marker of advanced fluency."},
                {"id": "c1cn26", "statement": "Ne and ci can both attach to an infinitive after a modal verb.", "answer": True, "explanation": "Both particles can attach to an infinitive, just like object pronouns."},
             ]},
        ],
        "summary": [
            "Va', da', fa', sta', di' double the first consonant of an attached pronoun — except gli, which never doubles.",
            "With modal + infinitive, pronouns (including combined ones) can attach to the infinitive or precede the modal.",
            "These fine points of pronoun placement are a genuine marker of fluent, C1-level control.",
        ],
    },
]
