# -*- coding: utf-8 -*-
"""C2 — Proficient curriculum data."""

OVERVIEW = ("C2 moves past the mechanics of grammar into control of style: complex syntax and "
            "inversion, literary and archaic register, precise collocations, cohesive devices for "
            "long texts, hedging and nuanced modality, and awareness of Italy's real linguistic "
            "variety. This is fluency as judgment, not just correctness.")

LESSONS = [
    {
        "id": "c2-sintassi-complessa",
        "level": "C2", "unit": "1", "order": 1, "skill": "grammar", "strand": "syntax",
        "title": "Sintassi Complessa e Inversione",
        "subtitle": "Reordering a sentence for emphasis, without breaking it.",
        "objectives": [
            "Use subject-verb inversion for stylistic emphasis in written Italian",
            "Front a subordinate clause or object for emphasis",
            "Recognize inversion after certain adverbs and in formal narrative style",
        ],
        "content": {
            "intro": "Standard Italian word order (subject-verb-object) is flexible enough that shifting an element to the front or inverting subject and verb reshapes emphasis — a tool fluent writers use deliberately.",
            "explanation": "<p>Fronting an object or subordinate clause pulls focus onto it: <em>Quello che mi preoccupa è il costo.</em> (What worries me is the cost — instead of <em>Il costo mi preoccupa.</em>) Certain adverbs and adverbial phrases at the start of a sentence trigger or favor inversion in more formal/literary registers: <em>Solo così si può capire davvero.</em> (Only in this way can one truly understand.)</p>",
            "rules": [
                {"heading": "a) Subject postponed for emphasis", "body": "<p><em>È arrivato il momento della verità.</em> (The moment of truth has arrived — subject after the verb, more dramatic than Il momento della verità è arrivato.)</p>"},
                {"heading": "b) Fronting for focus", "body": "<p><em>Di questo non voglio parlare.</em> (About this, I don't want to talk — object/prepositional phrase fronted for emphasis.)</p>"},
                {"heading": "c) Cleft sentences", "body": "<p><em>È proprio questo il punto.</em> (This is exactly the point.) <em>Fu allora che capii tutto.</em> (It was then that I understood everything.)</p>"},
            ],
            "examples": [
                {"it": "Solo allora capii la gravità della situazione.", "en": "Only then did I understand the seriousness of the situation."},
                {"it": "È il coraggio che ammiro di più in lei.", "en": "It's her courage that I admire most."},
                {"it": "Di soldi non ne aveva mai avuti molti.", "en": "Money, he had never had much of."},
                {"it": "Non appena arrivò la notizia, tutti tacquero.", "en": "As soon as the news arrived, everyone fell silent."},
            ],
            "commonMistakes": [
                {"wrong": "Overusing inversion in casual conversation", "right": "Reserve heavy inversion for formal writing/narrative", "why": "Constant inversion sounds stilted or overly literary in everyday spoken Italian — it's a stylistic register choice, not a default."},
                {"wrong": "È il coraggio che io ammiro di più in lei. (redundant pronoun)", "right": "È il coraggio che ammiro di più in lei.", "why": "In a cleft sentence like this, the subject pronoun io is typically dropped as usual — adding it back doesn't add emphasis, since the cleft structure itself already provides it."},
            ],
        },
        "exercises": [
            {"id": "c2sc-mc", "type": "multiple-choice", "title": "Identify the Emphasis Structure",
             "items": [
                {"id": "c2sc1", "prompt": "\"È proprio questo il problema.\" — What does this structure emphasize?", "options": ["The subject, questo/il problema", "Nothing in particular", "The verb only"], "answerIndex": 0, "explanation": "This is a cleft sentence, structurally designed to spotlight questo/il problema."},
                {"id": "c2sc2", "prompt": "Which register favors frequent subject-verb inversion?", "options": ["Casual texting", "Formal/literary narrative", "Everyday small talk"], "answerIndex": 1, "explanation": "Inversion for emphasis is a formal/literary stylistic device."},
             ]},
            {"id": "c2sc-correction", "type": "correction", "title": "Improve for Emphasis",
             "items": [
                {"id": "c2sc3", "incorrect": "Il coraggio è la qualità che ammiro di più in lei. (flat, no emphasis structure)", "answer": ["È il coraggio la qualità che ammiro di più in lei."], "explanation": "Fronting/clefting il coraggio sharpens the emphasis compared to the flat statement."},
             ]},
            {"id": "c2sc-fill2", "type": "fill-blank", "title": "More Emphasis Structures",
             "items": [
                {"id": "c2sc4", "prompt": "___ arrivò la sua occasione.", "answers": [["Solo allora"]], "explanation": "Solo allora fronts the adverb for emphasis.", "options": ["Solo allora", "Allora solo", "Poi"]},
                {"id": "c2sc5", "prompt": "Di lui non ___ (io - volere) più sentire parlare.", "answers": [["voglio"]], "explanation": "Fronted object (di lui), io form of volere.", "options": ["voglio", "vuoi", "vogliono"]},
                {"id": "c2sc6", "prompt": "___ (Arrivare) il momento della verità.", "answers": [["È arrivato"]], "explanation": "Subject postponed after the verb for drama.", "options": ["È arrivato", "Arriva", "Arrivò"]},
                {"id": "c2sc7", "prompt": "___ capii che avevo sbagliato tutto.", "answers": [["Fu allora che"]], "explanation": "Cleft sentence spotlighting the moment of realization.", "options": ["Fu allora che", "Allora che fu", "Quando fu"]},
                {"id": "c2sc8", "prompt": "È ___ che ammiro di più in lui.", "answers": [["proprio il coraggio"]], "explanation": "Cleft sentence fronting il coraggio for emphasis.", "options": ["proprio il coraggio", "il coraggio proprio", "coraggio proprio"]},
                {"id": "c2sc9", "prompt": "___ arrivò la notizia, tutti tacquero.", "answers": [["Non appena"]], "explanation": "Non appena is the fixed \"as soon as\" expression.", "options": ["Non appena", "Appena non", "Solo se"]},
                {"id": "c2sc10", "prompt": "Di soldi non ne ___ (avere) mai avuti molti.", "answers": [["aveva"]], "explanation": "Fronted topic (di soldi) + ne, imperfetto of avere.", "options": ["aveva", "ha", "ebbe"]},
                {"id": "c2sc11", "prompt": "___ questo il punto.", "answers": [["È proprio"]], "explanation": "Cleft sentence emphasizing questo.", "options": ["È proprio", "Proprio è", "Sta"]},
             ]},
            {"id": "c2sc-mc2", "type": "multiple-choice", "title": "More Emphasis Choices",
             "items": [
                {"id": "c2sc12", "prompt": "Fronting an object or subordinate clause has what effect?", "options": ["it shifts emphasis onto it", "it makes the sentence ungrammatical", "it removes all emphasis"], "answerIndex": 0, "explanation": "Fronting pulls focus onto the fronted element."},
                {"id": "c2sc13", "prompt": "\"Fu allora che capii tutto\" is an example of...", "options": ["a cleft sentence", "the passive voice", "the subjunctive"], "answerIndex": 0, "explanation": "This is a classic cleft-sentence structure."},
                {"id": "c2sc14", "prompt": "Which register typically uses heavy subject-verb inversion?", "options": ["formal/literary narrative", "texting", "casual small talk"], "answerIndex": 0, "explanation": "Inversion for emphasis belongs to formal/literary style."},
                {"id": "c2sc15", "prompt": "\"Di questo non voglio parlare\" fronts which element?", "options": ["a prepositional phrase/topic", "the subject", "the verb"], "answerIndex": 0, "explanation": "Di questo, a prepositional phrase, is fronted for emphasis."},
                {"id": "c2sc16", "prompt": "In a cleft sentence like \"È il coraggio che ammiro\", is the subject pronoun io typically kept?", "options": ["no, it's dropped as usual", "yes, always", "only in writing"], "answerIndex": 0, "explanation": "The cleft structure itself provides emphasis, so io stays dropped."},
                {"id": "c2sc17", "prompt": "\"È arrivato il momento della verità\" postpones which element?", "options": ["the subject", "the object", "the adverb"], "answerIndex": 0, "explanation": "The subject, il momento, comes after the verb for drama."},
                {"id": "c2sc18", "prompt": "Overusing inversion in casual conversation tends to sound...", "options": ["stilted/overly literary", "perfectly natural", "more polite"], "answerIndex": 0, "explanation": "Constant inversion reads as unnaturally formal in everyday speech."},
             ]},
            {"id": "c2sc-tf", "type": "true-false", "title": "True or False?",
             "items": [
                {"id": "c2sc19", "statement": "Standard word order in Italian is completely rigid, with no room for reordering.", "answer": False, "explanation": "Italian word order is flexible enough to reorder elements for emphasis."},
                {"id": "c2sc20", "statement": "Cleft sentences spotlight one specific element of the sentence.", "answer": True, "explanation": "That's exactly their function."},
                {"id": "c2sc21", "statement": "Heavy inversion is the everyday default in spoken Italian.", "answer": False, "explanation": "It's a formal/literary stylistic choice, not the everyday default."},
                {"id": "c2sc22", "statement": "\"Solo allora capii\" fronts an adverb for emphasis.", "answer": True, "explanation": "Solo allora is fronted to emphasize the timing."},
                {"id": "c2sc23", "statement": "Fronting an object always makes a sentence ungrammatical.", "answer": False, "explanation": "Fronting is a valid, grammatical stylistic device."},
                {"id": "c2sc24", "statement": "A cleft sentence typically uses è... che to isolate one element.", "answer": True, "explanation": "This is the standard cleft-sentence pattern."},
                {"id": "c2sc25", "statement": "Reordering for emphasis is a stylistic tool used deliberately by fluent writers.", "answer": True, "explanation": "Fluent writers use word order deliberately for effect."},
             ]},
        ],
        "summary": [
            "Fronting an object, subordinate clause, or adverbial phrase shifts emphasis onto it.",
            "Cleft sentences (è... che) spotlight one element of the sentence explicitly.",
            "Heavy inversion is a formal/literary register choice, not the everyday default.",
        ],
    },
    {
        "id": "c2-registro-letterario",
        "level": "C2", "unit": "1", "order": 2, "skill": "reading", "strand": "register",
        "title": "Registro Letterario e Forme Arcaiche",
        "subtitle": "Recognizing (not necessarily using) the Italian of literature and formal narration.",
        "objectives": [
            "Recognize the passato remoto and its role in literary narration",
            "Identify archaic/literary pronouns and vocabulary",
            "Read a short literary-register passage with comprehension",
        ],
        "content": {
            "intro": "Literary Italian preserves forms that have largely disappeared from speech — most importantly the passato remoto, still standard for narrating completed historical or fictional events at a narrative distance.",
            "explanation": "<p>The <strong>passato remoto</strong> is a simple (one-word) past tense, used in place of the passato prossimo for events felt as historically or narratively distant — literature, history books, some regional speech (especially southern Italy, where it remains common even in conversation). At C2, the goal is <em>recognition</em> for reading, not necessarily active production.</p>",
            "table": "<div class=\"table-scroll\"><table class=\"ref-table\"><caption>Passato remoto — parlare, credere, partire (recognition forms)</caption><thead><tr><th>Subject</th><th>parlare</th><th>credere</th><th>partire</th></tr></thead><tbody><tr><td>io</td><td>parlai</td><td>credei/credetti</td><td>partii</td></tr><tr><td>tu</td><td>parlasti</td><td>credesti</td><td>partisti</td></tr><tr><td>lui/lei</td><td>parlò</td><td>credé/credette</td><td>partì</td></tr><tr><td>noi</td><td>parlammo</td><td>credemmo</td><td>partimmo</td></tr><tr><td>voi</td><td>parlaste</td><td>credeste</td><td>partiste</td></tr><tr><td>loro</td><td>parlarono</td><td>crederono/credettero</td><td>partirono</td></tr></tbody></table></div>",
            "rules": [
                {"heading": "a) Where you'll meet it", "body": "<p>Novels, fairy tales (<em>C'era una volta... il principe partì...</em>), history books, formal biographical writing, and everyday conversation in much of southern Italy.</p>"},
                {"heading": "b) Archaic/literary vocabulary and forms", "body": "<p><em>ove</em> (dove, poetic), <em>giacché</em> (poiché), <em>dianzi</em> (poco fa), <em>egli/ella</em> (lui/lei, now purely literary), <em>testé</em> (proprio ora).</p>"},
            ],
            "examples": [
                {"it": "Nacque a Firenze nel 1265 e morì nel 1321.", "en": "He was born in Florence in 1265 and died in 1321. (biographical passato remoto)"},
                {"it": "Il re, udita la notizia, convocò subito il consiglio.", "en": "The king, having heard the news, immediately summoned the council."},
                {"it": "Ella non disse nulla e se ne andò in silenzio.", "en": "She said nothing and left in silence. (literary ella, not lei)"},
                {"it": "Giacché era tardi, decisero di rimandare la partenza.", "en": "Since it was late, they decided to postpone the departure."},
            ],
            "commonMistakes": [
                {"wrong": "Using the passato remoto for yesterday's events in everyday central/northern Italian conversation", "right": "Use the passato prossimo for recent events in everyday speech (outside southern regional use)", "why": "The passato remoto reads as narratively distant/literary in most of Italy — using it for something that happened yesterday sounds jarring outside its normal contexts."},
            ],
        },
        "exercises": [
            {"id": "c2rl-mc", "type": "multiple-choice", "title": "Reading Comprehension",
             "items": [
                {"id": "c2rl1", "prompt": "In \"Il re, udita la notizia, convocò subito il consiglio,\" what is convocò?", "options": ["Present tense of convocare", "Passato remoto of convocare", "Imperfetto of convocare"], "answerIndex": 1, "explanation": "Convocò is the third-person singular passato remoto of convocare."},
                {"id": "c2rl2", "prompt": "Where would you most expect to encounter the passato remoto?", "options": ["A casual text message", "A historical novel", "A shopping list"], "answerIndex": 1, "explanation": "The passato remoto is the standard narrative past of literature and history writing."},
             ]},
            {"id": "c2rl-match", "type": "matching", "title": "Match the Literary Form to Its Modern Equivalent",
             "items": [
                {"id": "c2rl3", "pairs": [
                    {"left": "ove", "right": "dove"},
                    {"left": "giacché", "right": "poiché"},
                    {"left": "egli/ella", "right": "lui/lei"},
                    {"left": "testé", "right": "proprio ora"},
                ], "explanation": "These literary forms are recognizable but no longer used in everyday spoken Italian."},
             ]},
            {"id": "c2rl-fill2", "type": "fill-blank", "title": "More Passato Remoto Practice",
             "items": [
                {"id": "c2rl4", "prompt": "Il poeta ___ (partire) all'alba.", "answers": [["partì"]], "explanation": "Passato remoto of partire, lui form.", "options": ["partì", "partiva", "è partito"]},
                {"id": "c2rl5", "prompt": "Noi ___ (credere) subito alle sue parole.", "answers": [["credemmo"]], "explanation": "Passato remoto of credere, noi form.", "options": ["credemmo", "credevamo", "abbiamo creduto"]},
                {"id": "c2rl6", "prompt": "___ non disse nulla. (literary word for \"she\")", "answers": [["Ella"]], "explanation": "Ella is the literary equivalent of lei.", "options": ["Ella", "Lei", "Essa"]},
                {"id": "c2rl7", "prompt": "___, era tardi per tornare indietro. (since, literary)", "answers": [["Giacché", "Poiché"]], "explanation": "Giacché is a literary equivalent of poiché.", "options": ["Giacché", "Ove", "Testé"]},
                {"id": "c2rl8", "prompt": "Il re ___ (convocare) subito il consiglio.", "answers": [["convocò"]], "explanation": "Passato remoto of convocare, lui form.", "options": ["convocò", "convocava", "ha convocato"]},
             ]},
            {"id": "c2rl-mc2", "type": "multiple-choice", "title": "More Literary Register Choices",
             "items": [
                {"id": "c2rl9", "prompt": "Which tense is standard for narrating historical/fictional events at a distance?", "options": ["passato remoto", "presente", "futuro"], "answerIndex": 0, "explanation": "The passato remoto is the narrative past of literature and history."},
                {"id": "c2rl10", "prompt": "Where does the passato remoto remain common even in everyday conversation?", "options": ["much of southern Italy", "northern Italy exclusively", "only in poetry"], "answerIndex": 0, "explanation": "Southern regional speech keeps the passato remoto in everyday use."},
                {"id": "c2rl11", "prompt": "\"Ove\" is the literary equivalent of which word?", "options": ["dove", "chi", "quando"], "answerIndex": 0, "explanation": "Ove is a poetic form of dove."},
                {"id": "c2rl12", "prompt": "\"Testé\" is the literary equivalent of...", "options": ["proprio ora", "molto tempo fa", "mai"], "answerIndex": 0, "explanation": "Testé means \"just now\"."},
                {"id": "c2rl13", "prompt": "At C2, the goal with the passato remoto is...", "options": ["recognition for reading, not necessarily active production", "full active mastery in speech", "avoiding it entirely"], "answerIndex": 0, "explanation": "Reading recognition is the realistic C2 goal for this tense."},
                {"id": "c2rl14", "prompt": "\"Egli/ella\" are literary equivalents of...", "options": ["lui/lei", "tu/voi", "noi/loro"], "answerIndex": 0, "explanation": "Egli/ella are the literary forms of lui/lei."},
             ]},
            {"id": "c2rl-tf", "type": "true-false", "title": "True or False?",
             "items": [
                {"id": "c2rl15", "statement": "The passato remoto has entirely disappeared from spoken Italian everywhere.", "answer": False, "explanation": "It remains common in everyday speech in much of southern Italy."},
                {"id": "c2rl16", "statement": "Egli/ella are now purely literary, replaced by lui/lei in everyday speech.", "answer": True, "explanation": "This is exactly their current status."},
                {"id": "c2rl17", "statement": "Using the passato remoto for yesterday's events in casual northern conversation sounds natural.", "answer": False, "explanation": "It reads as jarringly literary/distant outside its normal contexts."},
                {"id": "c2rl18", "statement": "Giacché is a literary equivalent of poiché.", "answer": True, "explanation": "Both introduce a cause, giacché being more literary."},
                {"id": "c2rl19", "statement": "Fairy tales commonly use the passato remoto.", "answer": True, "explanation": "\"Il principe partì...\" is a classic fairy-tale use."},
             ]},
        ],
        "summary": [
            "The passato remoto is the standard narrative past of literature, history, and (regionally) southern Italian speech.",
            "C2 reading fluency requires recognizing it and a handful of archaic pronouns/connectors, even without actively using them.",
            "Using literary forms in ordinary conversation outside their natural context sounds stilted or affected.",
        ],
    },
    {
        "id": "c2-sfumature-lessicali",
        "level": "C2", "unit": "1", "order": 3, "skill": "vocabulary", "strand": "lexis",
        "title": "Sfumature Lessicali e Collocazioni",
        "subtitle": "Near-synonyms that aren't interchangeable, and the fixed word pairings native speakers expect.",
        "objectives": [
            "Distinguish near-synonym pairs by register, connotation, or precise meaning",
            "Use common fixed collocations correctly",
            "Avoid literal word-for-word translation from English collocations",
        ],
        "content": {
            "intro": "At C2, correctness alone isn't enough — native-like Italian depends on choosing the word a native speaker would actually reach for, in the exact combination they expect.",
            "explanation": "<p>Many Italian near-synonyms differ by connotation, formality, or precise shade of meaning — not by strict correctness. Collocations (fixed word pairings, like English \"heavy rain\" rather than \"strong rain\") are equally important and rarely translate literally from English.</p>",
            "rules": [
                {"heading": "a) Near-synonym pairs", "body": "<ul><li><em>lavoro</em> (neutral) vs. <em>occupazione</em> (more formal/administrative) vs. <em>impiego</em> (a specific job/position)</li><li><em>felice</em> (deep, meaningful happiness) vs. <em>contento</em> (satisfied, more everyday)</li><li><em>guardare</em> (to look at, active) vs. <em>vedere</em> (to see, perceive)</li></ul>"},
                {"heading": "b) Fixed collocations", "body": "<p><em>fare una domanda</em> (to ask a question, not \"chiedere una domanda\"); <em>prendere una decisione</em> (to make a decision, not \"fare una decisione\"); <em>commettere un errore</em> (to make a mistake, not \"fare un errore\", though this is now widely tolerated); <em>pioggia battente</em> (pouring rain, not \"pioggia forte\").</p>"},
            ],
            "examples": [
                {"it": "Ho preso una decisione difficile.", "en": "I made a difficult decision."},
                {"it": "Mi ha fatto una domanda imbarazzante.", "en": "He asked me an embarrassing question."},
                {"it": "Ha commesso un grave errore di valutazione.", "en": "He made a serious error of judgment."},
                {"it": "Sono felice di essere qui con voi stasera.", "en": "I am [deeply] happy to be here with you tonight."},
            ],
            "commonMistakes": [
                {"wrong": "Ho fatto una decisione.", "right": "Ho preso una decisione.", "why": "Decisions are \"taken\" (prendere), not \"made\" (fare), in standard Italian — a direct calque from English fails here."},
                {"wrong": "Mi ha chiesto una domanda.", "right": "Mi ha fatto una domanda.", "why": "Questions are \"made/asked\" with fare, not chiedere — chiedere una domanda is a common learner error, redundant in meaning too."},
            ],
        },
        "exercises": [
            {"id": "c2sl-fill", "type": "fill-blank", "title": "Fill in the Correct Collocation",
             "items": [
                {"id": "c2sl1", "prompt": "Devo ___ una decisione importante.", "answers": [["prendere"]], "explanation": "Prendere una decisione is the fixed collocation.", "options": ["prendere", "fare", "dare"]},
                {"id": "c2sl2", "prompt": "Posso ___ ti una domanda?", "answers": [["fare"]], "explanation": "Fare una domanda is the fixed collocation.", "options": ["fare", "chiedere", "dire"]},
             ]},
            {"id": "c2sl-mc", "type": "multiple-choice", "title": "Choose the Better Word",
             "items": [
                {"id": "c2sl3", "prompt": "Describing torrential rain: \"pioggia ___\"", "options": ["forte", "battente", "grande"], "answerIndex": 1, "explanation": "Pioggia battente is the natural collocation for heavy, driving rain."},
             ]},
            {"id": "c2sl-fill2", "type": "fill-blank", "title": "More Collocation Practice",
             "items": [
                {"id": "c2sl4", "prompt": "Ha ___ un grave errore di valutazione.", "answers": [["commesso"]], "explanation": "Commettere un errore is the standard collocation.", "options": ["commesso", "fatto", "preso"]},
                {"id": "c2sl5", "prompt": "Sono ___ di aver superato l'esame, ma non è la gioia della mia vita.", "answers": [["contento", "contenta"]], "explanation": "Contento fits everyday satisfaction, not the deeper felice.", "options": ["contento", "felice", "impiegato"]},
                {"id": "c2sl6", "prompt": "Il meteorologo prevede ___ battente per stasera.", "answers": [["pioggia"]], "explanation": "Pioggia battente is the fixed collocation for heavy rain.", "options": ["pioggia", "acqua", "tempesta"]},
                {"id": "c2sl7", "prompt": "Devo ___ una decisione entro domani.", "answers": [["prendere"]], "explanation": "Prendere una decisione is the fixed collocation.", "options": ["prendere", "fare", "dare"]},
                {"id": "c2sl8", "prompt": "Mi ha ___ una domanda molto difficile.", "answers": [["fatto"]], "explanation": "Fare una domanda is the fixed collocation.", "options": ["fatto", "chiesto", "detto"]},
                {"id": "c2sl9", "prompt": "Cerca un ___ stabile, non solo un lavoro part-time.", "answers": [["impiego"]], "explanation": "Impiego denotes a specific job/position, more precisely than lavoro.", "options": ["impiego", "lavoro", "occupazione"]},
             ]},
            {"id": "c2sl-mc2", "type": "multiple-choice", "title": "More Word Choice Practice",
             "items": [
                {"id": "c2sl10", "prompt": "Which verb pairs with \"una decisione\" in standard Italian?", "options": ["prendere", "fare", "dare"], "answerIndex": 0, "explanation": "Prendere una decisione is the fixed collocation."},
                {"id": "c2sl11", "prompt": "Which verb pairs with \"una domanda\"?", "options": ["fare", "chiedere", "dire"], "answerIndex": 0, "explanation": "Fare una domanda is the fixed collocation."},
                {"id": "c2sl12", "prompt": "Which word describes a specific job/position, more precisely than \"lavoro\"?", "options": ["impiego", "occupazione", "fatica"], "answerIndex": 0, "explanation": "Impiego is the more precise, specific word."},
                {"id": "c2sl13", "prompt": "\"Guardare\" vs. \"vedere\" — which is the active, deliberate act of looking?", "options": ["guardare", "vedere", "entrambi uguali"], "answerIndex": 0, "explanation": "Guardare is active looking; vedere is passive perceiving."},
                {"id": "c2sl14", "prompt": "Which collocation describes heavy, driving rain?", "options": ["pioggia battente", "pioggia forte", "pioggia grande"], "answerIndex": 0, "explanation": "Pioggia battente is the natural, fixed collocation."},
                {"id": "c2sl15", "prompt": "Direct calques from English collocations are...", "options": ["a persistent tell of a non-native speaker", "always acceptable", "preferred in formal writing"], "answerIndex": 0, "explanation": "Calques like fare una decisione mark non-native speech."},
             ]},
            {"id": "c2sl-tf", "type": "true-false", "title": "True or False?",
             "items": [
                {"id": "c2sl16", "statement": "Fare una decisione is the standard, correct collocation.", "answer": False, "explanation": "The standard collocation is prendere una decisione."},
                {"id": "c2sl17", "statement": "Chiedere una domanda is a common learner error.", "answer": True, "explanation": "Fare una domanda is the correct, native collocation."},
                {"id": "c2sl18", "statement": "Felice and contento are always fully interchangeable, with no difference in connotation.", "answer": False, "explanation": "Felice implies deeper happiness; contento is more everyday satisfaction."},
                {"id": "c2sl19", "statement": "Collocations rarely translate literally from English.", "answer": True, "explanation": "This is exactly why calques from English tend to fail."},
                {"id": "c2sl20", "statement": "Commettere un errore is the standard collocation for making a mistake.", "answer": True, "explanation": "This is the standard, expected pairing."},
                {"id": "c2sl21", "statement": "Near-synonyms in Italian can differ by register or connotation rather than strict correctness.", "answer": True, "explanation": "This is the core lesson of this unit."},
             ]},
        ],
        "summary": [
            "Near-synonyms often differ by register or connotation rather than strict correctness — precise use is a C2 marker.",
            "Collocations are fixed word pairings (prendere una decisione, fare una domanda) that rarely translate literally.",
            "Direct calques from English collocations are one of the most persistent tells of a non-native speaker.",
        ],
    },
    {
        "id": "c2-sintesi-argomentazione",
        "level": "C2", "unit": "1", "order": 4, "skill": "writing", "strand": "argumentation",
        "title": "L'Arte della Sintesi: Riassumere e Argomentare",
        "subtitle": "Structuring a persuasive argument and summarizing precisely.",
        "objectives": [
            "Structure a short argumentative text with thesis, evidence, and counterargument",
            "Use hedging and concession to acknowledge an opposing view before rebutting it",
            "Summarize a longer text concisely without losing its key claims",
        ],
        "content": {
            "intro": "Real argumentative writing in Italian doesn't just state opinions — it anticipates and addresses the other side, using concession as a rhetorical tool rather than a weakness.",
            "explanation": "<p>A strong argumentative paragraph typically states a thesis, concedes a point to the opposing view (<em>È vero che..., Non si può negare che...</em>), and then pivots to the counter-argument (<em>Tuttavia..., Ciononostante...</em>). Summarizing well means compressing a text to its core claims without adding opinion or losing the original logical structure.</p>",
            "rules": [
                {"heading": "a) Concession + rebuttal structure", "body": "<p><em>È vero che [concession], tuttavia [counter-argument].</em> <em>Sebbene si possa obiettare che..., resta il fatto che...</em></p>"},
                {"heading": "b) Summarizing formulas", "body": "<p><em>L'autore sostiene che... / Il testo affronta il tema di... / In sintesi, l'argomento centrale è...</em></p>"},
            ],
            "examples": [
                {"it": "È vero che il progetto comporta dei rischi; tuttavia, i benefici a lungo termine superano di gran lunga i costi iniziali.", "en": "It's true the project carries risks; however, the long-term benefits far outweigh the initial costs."},
                {"it": "L'autore sostiene che la tecnologia, se usata con moderazione, possa migliorare la qualità della vita.", "en": "The author argues that technology, if used in moderation, can improve quality of life."},
                {"it": "Sebbene si possa obiettare che la misura sia costosa, resta il fatto che salverebbe molte vite.", "en": "Although one might object that the measure is expensive, the fact remains it would save many lives."},
            ],
            "commonMistakes": [
                {"wrong": "Ignoring the counterargument entirely in a persuasive text", "right": "Acknowledge it explicitly (è vero che...) before rebutting", "why": "A persuasive argument that never addresses the obvious objection reads as one-sided and less convincing at this level of writing."},
                {"wrong": "Summarizing by copying full sentences from the original", "right": "Restate the core claim in your own, more compressed words", "why": "A genuine summary requires reformulation, not verbatim extraction — copying isn't synthesis."},
            ],
        },
        "exercises": [
            {"id": "c2sa-mc", "type": "multiple-choice", "title": "Identify the Rhetorical Move",
             "items": [
                {"id": "c2sa1", "prompt": "\"È vero che... tuttavia...\" is an example of:", "options": ["A simple statement of fact", "Concession followed by rebuttal", "A summary formula"], "answerIndex": 1, "explanation": "This is the classic concession + counter-argument structure."},
             ]},
            {"id": "c2sa-fill", "type": "fill-blank", "title": "Complete the Argumentative Structure",
             "items": [
                {"id": "c2sa2", "prompt": "___ si possa obiettare che il piano sia rischioso, i vantaggi sono evidenti. (although)", "answers": [["Sebbene", "Benché"]], "explanation": "Concessive conjunction, subjunctive follows.", "options": ["Sebbene", "Perché", "Quindi"]},
            ]},
            {"id": "c2sa-fill2", "type": "fill-blank", "title": "More Argumentative Structure Practice",
             "items": [
                {"id": "c2sa3", "prompt": "___ che il piano comporti dei rischi, i benefici superano i costi.", "answers": [["È vero"]], "explanation": "È vero che opens a concession.", "options": ["È vero", "Non è vero", "Forse"]},
                {"id": "c2sa4", "prompt": "L'autore ___ (sostenere) che la tecnologia migliori la vita.", "answers": [["sostiene"]], "explanation": "Sostiene is the standard summarizing verb form.", "options": ["sostiene", "sostenga", "ha sostenuto"]},
                {"id": "c2sa5", "prompt": "In ___, l'argomento centrale del testo è la sostenibilità.", "answers": [["sintesi"]], "explanation": "In sintesi is a standard summarizing formula.", "options": ["sintesi", "conclusione", "fine"]},
                {"id": "c2sa6", "prompt": "___ si possa obiettare che sia costoso, resta il fatto che funziona.", "answers": [["Sebbene", "Benché"]], "explanation": "Concessive conjunction, subjunctive follows.", "options": ["Sebbene", "Quindi", "Poiché"]},
                {"id": "c2sa7", "prompt": "Il testo ___ (affrontare) il tema della disuguaglianza.", "answers": [["affronta"]], "explanation": "Affronta is the standard summarizing verb form.", "options": ["affronta", "affrontò", "ha affrontato"]},
                {"id": "c2sa8", "prompt": "Non si può ___ che il progetto abbia dei limiti.", "answers": [["negare"]], "explanation": "Non si può negare che is a fixed concession formula.", "options": ["negare", "dire", "fare"]},
                {"id": "c2sa9", "prompt": "___, i benefici a lungo termine superano i costi iniziali.", "answers": [["Tuttavia", "Ciononostante"]], "explanation": "These introduce the rebuttal after a concession.", "options": ["Tuttavia", "Poiché", "Infine"]},
             ]},
            {"id": "c2sa-mc2", "type": "multiple-choice", "title": "More Rhetorical Move Choices",
             "items": [
                {"id": "c2sa10", "prompt": "A strong argumentative paragraph typically starts with...", "options": ["a thesis", "a summary", "a question only"], "answerIndex": 0, "explanation": "A clear thesis anchors the rest of the argument."},
                {"id": "c2sa11", "prompt": "\"Non si può negare che...\" functions as...", "options": ["a concession", "a rebuttal", "a summary formula"], "answerIndex": 0, "explanation": "It concedes a point before the pivot to rebuttal."},
                {"id": "c2sa12", "prompt": "Which formula introduces a text's central claim in a summary?", "options": ["l'autore sostiene che", "tuttavia", "sebbene"], "answerIndex": 0, "explanation": "This is a standard summarizing formula."},
                {"id": "c2sa13", "prompt": "What should a genuine summary avoid?", "options": ["copying full sentences from the original", "using your own words", "being concise"], "answerIndex": 0, "explanation": "A summary requires reformulation, not verbatim extraction."},
                {"id": "c2sa14", "prompt": "Which structure acknowledges an opposing view before rebutting it?", "options": ["concession + rebuttal", "summary + conclusion", "question + answer"], "answerIndex": 0, "explanation": "This is the classic argumentative structure."},
                {"id": "c2sa15", "prompt": "Ignoring the counterargument in persuasive writing tends to make it...", "options": ["one-sided and less convincing", "more convincing", "irrelevant"], "answerIndex": 0, "explanation": "Ignoring objections weakens persuasive writing."},
                {"id": "c2sa16", "prompt": "\"Ciononostante\" is closest in meaning to...", "options": ["tuttavia", "poiché", "infine"], "answerIndex": 0, "explanation": "Both introduce a contrast/rebuttal."},
             ]},
            {"id": "c2sa-tf", "type": "true-false", "title": "True or False?",
             "items": [
                {"id": "c2sa17", "statement": "A persuasive argument should ignore the obvious objection to stay strong.", "answer": False, "explanation": "Addressing the objection explicitly makes the argument stronger, not weaker."},
                {"id": "c2sa18", "statement": "Summarizing means restating core claims in your own, compressed words.", "answer": True, "explanation": "This is the definition of genuine synthesis."},
                {"id": "c2sa19", "statement": "È vero che... tuttavia... is a concession + rebuttal structure.", "answer": True, "explanation": "This is the classic pattern taught in this lesson."},
                {"id": "c2sa20", "statement": "L'autore sostiene che is a formula used to introduce someone else's argument.", "answer": True, "explanation": "It reports the author's claim in a summary."},
                {"id": "c2sa21", "statement": "Copying full sentences from a text counts as a valid summary.", "answer": False, "explanation": "A genuine summary requires reformulation, not verbatim copying."},
                {"id": "c2sa22", "statement": "Hedging and concession are used as rhetorical tools, not signs of weakness.", "answer": True, "explanation": "They strengthen an argument by anticipating objections."},
             ]},
        ],
        "summary": [
            "Strong argumentative writing concedes a point to the opposing view before rebutting it with tuttavia/ciononostante.",
            "Summarizing means restating core claims in compressed, original wording — not copying sentences.",
            "Set formulas (l'autore sostiene che, in sintesi) structure both argument and summary clearly.",
        ],
    },
    {
        "id": "c2-modalita-attenuazione",
        "level": "C2", "unit": "1", "order": 5, "skill": "grammar", "strand": "modality",
        "title": "Modalità e Attenuazione",
        "subtitle": "Hedging a claim, softening a criticism, and expressing calibrated certainty.",
        "objectives": [
            "Use hedging expressions to soften a claim or opinion",
            "Calibrate certainty with modal expressions (sembra che, pare che, a quanto pare)",
            "Soften criticism or disagreement diplomatically",
        ],
        "content": {
            "intro": "Native fluency includes knowing how to avoid sounding too blunt or too certain — Italian has a rich set of hedging tools for exactly this.",
            "explanation": "<p>Hedging expressions distance the speaker slightly from a claim, making room for doubt or diplomacy. Many pair naturally with the subjunctive (since they present something as less than certain fact).</p>",
            "rules": [
                {"heading": "a) Softening certainty", "body": "<p><em>Sembra che, pare che</em> + congiuntivo (it seems that); <em>a quanto pare, a quanto sembra</em> (apparently, + indicative); <em>Direi che...</em> (I'd say that..., conditional softening).</p>"},
                {"heading": "b) Softening disagreement/criticism", "body": "<p><em>Non sono del tutto d'accordo...</em> (I don't entirely agree...); <em>Forse potremmo considerare anche...</em> (Perhaps we could also consider...); <em>Non vorrei sembrare scortese, ma...</em> (I don't want to seem rude, but...)</p>"},
                {"heading": "c) Impersonal hedges", "body": "<p><em>Si direbbe che...</em> (One might say that...); <em>Non è escluso che...</em> (It's not out of the question that...)</p>"},
            ],
            "examples": [
                {"it": "Sembra che il progetto sia stato rimandato.", "en": "It seems the project has been postponed."},
                {"it": "A quanto pare, la riunione è stata spostata a venerdì.", "en": "Apparently, the meeting has been moved to Friday."},
                {"it": "Non vorrei sembrare polemico, ma non sono del tutto d'accordo.", "en": "I don't want to seem argumentative, but I don't entirely agree."},
                {"it": "Direi che è la soluzione migliore, anche se non l'unica possibile.", "en": "I'd say it's the best solution, though not the only possible one."},
            ],
            "commonMistakes": [
                {"wrong": "Sembra che il progetto è stato rimandato.", "right": "Sembra che il progetto sia stato rimandato.", "why": "Sembra che presents something as less than certain, triggering the subjunctive, unlike a quanto pare, which takes the indicative."},
                {"wrong": "Sei sbagliato. (blunt, unhedged disagreement)", "right": "Non sono del tutto d'accordo, credo che...", "why": "Bluntly telling someone they're wrong reads as impolite in most registers — hedged disagreement is the diplomatic, native-like default."},
            ],
        },
        "exercises": [
            {"id": "c2ma-fill", "type": "fill-blank", "title": "Fill in the Blanks",
             "items": [
                {"id": "c2ma1", "prompt": "Pare che la situazione ___ (migliorare) negli ultimi giorni.", "answers": [["sia migliorata"]], "explanation": "Pare che triggers the subjunctive.", "options": ["sia migliorata", "è migliorata", "migliora"]},
                {"id": "c2ma2", "prompt": "A quanto ___, il volo è stato cancellato. (apparently)", "answers": [["pare", "sembra"]], "explanation": "A quanto pare/sembra takes the indicative that follows normally (here already given as a fact statement).", "options": ["pare", "sia", "sembri"]},
             ]},
            {"id": "c2ma-mc", "type": "multiple-choice", "title": "Choose the More Diplomatic Option",
             "items": [
                {"id": "c2ma3", "prompt": "Disagreeing politely in a meeting:", "options": ["Non è vero.", "Non sono del tutto d'accordo, se posso dire.", "Ti sbagli."], "answerIndex": 1, "explanation": "Hedged disagreement is the diplomatically appropriate register."},
             ]},
            {"id": "c2ma-fill2", "type": "fill-blank", "title": "More Hedging Practice",
             "items": [
                {"id": "c2ma4", "prompt": "___ che la riunione ___ (essere) rimandata.", "answers": [["Sembra"], ["sia"]], "explanation": "Sembra che triggers the subjunctive.", "options": ["Sembra", "Pare", "sia", "è"]},
                {"id": "c2ma5", "prompt": "___ potremmo considerare anche altre opzioni.", "answers": [["Forse"]], "explanation": "Forse softens a suggestion.", "options": ["Forse", "Sicuramente", "Certamente"]},
                {"id": "c2ma6", "prompt": "Non ___ del tutto d'accordo con questa proposta.", "answers": [["sono"]], "explanation": "Non sono del tutto d'accordo is hedged disagreement.", "options": ["sono", "sto", "ho"]},
                {"id": "c2ma7", "prompt": "___ che il volo sia stato cancellato.", "answers": [["Pare"]], "explanation": "Pare che triggers the subjunctive.", "options": ["Pare", "A quanto pare", "Certamente"]},
                {"id": "c2ma8", "prompt": "Non vorrei ___ scortese, ma non sono d'accordo.", "answers": [["sembrare"]], "explanation": "Non vorrei sembrare softens the criticism.", "options": ["sembrare", "essere", "fare"]},
                {"id": "c2ma9", "prompt": "___ che si possa fare di meglio.", "answers": [["Si direbbe"]], "explanation": "Si direbbe che is an impersonal hedge.", "options": ["Si direbbe", "Si dice", "Si fa"]},
                {"id": "c2ma10", "prompt": "Non è ___ che il progetto venga approvato.", "answers": [["escluso"]], "explanation": "Non è escluso che means \"it's not out of the question\".", "options": ["escluso", "sicuro", "vero"]},
             ]},
            {"id": "c2ma-mc2", "type": "multiple-choice", "title": "More Hedging Choices",
             "items": [
                {"id": "c2ma11", "prompt": "Which expression takes the subjunctive to soften certainty?", "options": ["sembra che", "a quanto pare", "sicuramente"], "answerIndex": 0, "explanation": "Sembra che presents something as less than certain, triggering the subjunctive."},
                {"id": "c2ma12", "prompt": "Which expression is a fixed indicative alternative meaning \"apparently\"?", "options": ["a quanto pare", "sembra che", "pare che"], "answerIndex": 0, "explanation": "A quanto pare takes the indicative."},
                {"id": "c2ma13", "prompt": "\"Direi che...\" softens a claim using which mood?", "options": ["the conditional", "the subjunctive", "the imperative"], "answerIndex": 0, "explanation": "Direi is the conditional of dire, softening the claim."},
                {"id": "c2ma14", "prompt": "Which is the most diplomatic way to disagree?", "options": ["Non sono del tutto d'accordo...", "Ti sbagli.", "Non è vero."], "answerIndex": 0, "explanation": "Hedged disagreement is the diplomatic default."},
                {"id": "c2ma15", "prompt": "\"Non vorrei sembrare scortese, ma...\" is used to...", "options": ["soften criticism diplomatically", "give a blunt order", "express certainty"], "answerIndex": 0, "explanation": "It diplomatically prefaces a criticism or disagreement."},
                {"id": "c2ma16", "prompt": "\"Non è escluso che...\" means...", "options": ["it's not out of the question that...", "it's certain that...", "it's forbidden that..."], "answerIndex": 0, "explanation": "This impersonal hedge leaves room for possibility."},
                {"id": "c2ma17", "prompt": "Hedging expressions generally...", "options": ["distance the speaker slightly from a claim", "make a claim more certain", "are only used in writing"], "answerIndex": 0, "explanation": "Hedges create diplomatic distance from a full commitment to a claim."},
             ]},
            {"id": "c2ma-tf", "type": "true-false", "title": "True or False?",
             "items": [
                {"id": "c2ma18", "statement": "Sembra che and pare che both trigger the subjunctive.", "answer": True, "explanation": "Both present something as less than certain fact."},
                {"id": "c2ma19", "statement": "A quanto pare takes the subjunctive, just like sembra che.", "answer": False, "explanation": "A quanto pare takes the indicative, unlike sembra che."},
                {"id": "c2ma20", "statement": "Bluntly telling someone they're wrong is the diplomatic default in Italian.", "answer": False, "explanation": "Hedged disagreement is the diplomatic, native-like default."},
                {"id": "c2ma21", "statement": "Hedging is a marker of native-like social fluency.", "answer": True, "explanation": "Calibrating certainty and softening criticism mark advanced fluency."},
                {"id": "c2ma22", "statement": "Si direbbe che is an impersonal hedging expression.", "answer": True, "explanation": "It's a standard impersonal hedge."},
                {"id": "c2ma23", "statement": "Calibrating certainty is only relevant in written Italian, not spoken.", "answer": False, "explanation": "It's relevant in both spoken and written registers."},
                {"id": "c2ma24", "statement": "Softening criticism diplomatically is common in professional/social contexts.", "answer": True, "explanation": "This is a common, expected social skill."},
             ]},
        ],
        "summary": [
            "Sembra che/pare che soften certainty and trigger the subjunctive; a quanto pare is a fixed indicative alternative.",
            "Hedged disagreement (non sono del tutto d'accordo) is the diplomatic default, not blunt contradiction.",
            "Calibrating certainty and softening criticism are markers of genuinely native-like social fluency.",
        ],
    },
    {
        "id": "c2-coesione-testuale",
        "level": "C2", "unit": "1", "order": 6, "skill": "writing", "strand": "cohesion",
        "title": "Coesione Testuale Avanzata: Anafora ed Ellissi",
        "subtitle": "Keeping a long text connected without repeating yourself.",
        "objectives": [
            "Use anaphoric reference (pronouns, demonstratives) to avoid repetition across sentences",
            "Recognize and use ellipsis to omit a repeated element cleanly",
            "Maintain clarity of reference across a multi-sentence paragraph",
        ],
        "content": {
            "intro": "A cohesive text avoids repeating the same noun sentence after sentence, but also avoids ambiguity about what each pronoun refers back to — a balance advanced writing has to manage deliberately.",
            "explanation": "<p><strong>Anaphora</strong> here means referring back to something already mentioned, using a pronoun, demonstrative (<em>questo/quello</em>), or a summarizing noun (<em>tale scelta, questo fatto</em>) instead of repeating it. <strong>Ellipsis</strong> is the clean omission of a repeated element when the grammar makes it recoverable: <em>Marco studia legge, Anna [studia] medicina.</em></p>",
            "rules": [
                {"heading": "a) Anaphoric devices", "body": "<ul><li>Pronouns: <em>lo, la, li, le, ne, ci</em></li><li>Demonstratives: <em>questo, quello, ciò</em> (ciò is a fixed, invariable \"this/that [abstract idea]\")</li><li>Summarizing nouns: <em>tale decisione, questo approccio, il tutto</em></li></ul>"},
                {"heading": "b) Ellipsis", "body": "<p>Omitting a repeated verb (or verb phrase) when context makes it recoverable: <em>Lui ama la musica classica, lei [ama] il jazz.</em></p>"},
                {"heading": "c) Avoiding ambiguous reference", "body": "<p>When two possible antecedents exist, prefer a demonstrative or a repeated noun over an ambiguous pronoun: <em>Marco ha parlato con Luca; quest'ultimo sembrava preoccupato.</em> (quest'ultimo = \"the latter\", unambiguous.)</p>"},
            ],
            "examples": [
                {"it": "Il progetto è ambizioso. Ciò non significa che sia irrealizzabile.", "en": "The project is ambitious. That doesn't mean it's unachievable."},
                {"it": "Marco preferisce il tè, Anna il caffè.", "en": "Marco prefers tea, Anna [prefers] coffee. (ellipsis)"},
                {"it": "Ho parlato con il direttore e con il suo assistente; quest'ultimo si è mostrato molto disponibile.", "en": "I spoke with the director and his assistant; the latter was very helpful. (unambiguous anaphora)"},
                {"it": "Tale scelta ha sorpreso molti osservatori.", "en": "This choice surprised many observers. (summarizing anaphora)"},
            ],
            "commonMistakes": [
                {"wrong": "Repeating the full noun phrase in every sentence of a paragraph", "right": "Vary with pronouns, demonstratives, and summarizing nouns", "why": "Constant repetition of the same full noun phrase reads as mechanical and unpolished in fluent written Italian."},
                {"wrong": "Using lui/lei ambiguously when two people of the same gender were just mentioned", "right": "Use quest'ultimo/quel primo or repeat the name for clarity", "why": "An ambiguous pronoun with two possible antecedents forces the reader to guess — advanced writing resolves this explicitly."},
            ],
        },
        "exercises": [
            {"id": "c2ct-mc", "type": "multiple-choice", "title": "Choose the Best Cohesive Device",
             "items": [
                {"id": "c2ct1", "prompt": "Two people were just mentioned; you need to refer unambiguously to the second one:", "options": ["lui", "quest'ultimo", "quello"], "answerIndex": 1, "explanation": "Quest'ultimo (\"the latter\") unambiguously points to the most recently mentioned of the two."},
             ]},
            {"id": "c2ct-fill", "type": "fill-blank", "title": "Fill in the Blanks",
             "items": [
                {"id": "c2ct2", "prompt": "Il piano è complesso. ___ non lo rende impossibile. (this [abstract])", "answers": [["Ciò"]], "explanation": "Ciò is the fixed, invariable pronoun for an abstract \"this/that idea\".", "options": ["Ciò", "Questo oggetto", "Lui"]},
             ]},
            {"id": "c2ct-fill2", "type": "fill-blank", "title": "More Cohesion Practice",
             "items": [
                {"id": "c2ct3", "prompt": "Il piano è ambizioso. ___ non significa che sia irrealizzabile.", "answers": [["Ciò"]], "explanation": "Ciò refers back to the abstract idea just stated.", "options": ["Ciò", "Questo oggetto", "Lui"]},
                {"id": "c2ct4", "prompt": "Ho parlato con Marco e con Luca; ___ sembrava preoccupato.", "answers": [["quest'ultimo"]], "explanation": "Quest'ultimo unambiguously refers to Luca, the most recently mentioned.", "options": ["quest'ultimo", "lui", "quello"]},
                {"id": "c2ct5", "prompt": "___ scelta ha sorpreso molti osservatori.", "answers": [["Tale"]], "explanation": "Tale is a summarizing anaphoric device.", "options": ["Tale", "Questo", "Quello"]},
                {"id": "c2ct6", "prompt": "Il costo è aumentato molto. ___ fatto preoccupa gli investitori.", "answers": [["Questo"]], "explanation": "Questo summarizes the previous statement.", "options": ["Questo", "Ciò stesso", "Tale che"]},
                {"id": "c2ct7", "prompt": "Ho conosciuto due candidati; ___ mi ha convinto di più.", "answers": [["quest'ultimo"]], "explanation": "Quest'ultimo avoids ambiguity between the two candidates.", "options": ["quest'ultimo", "lui", "esso"]},
                {"id": "c2ct8", "prompt": "Il progetto è rischioso, ma ___ non lo rende inutile.", "answers": [["ciò"]], "explanation": "Ciò refers back to the abstract idea of riskiness.", "options": ["ciò", "questo oggetto", "essa"]},
                {"id": "c2ct9", "prompt": "___ approccio è stato criticato da molti esperti.", "answers": [["Questo", "Tale"]], "explanation": "Questo/tale summarize a previously described approach.", "options": ["Questo", "Lui", "Loro"]},
             ]},
            {"id": "c2ct-mc2", "type": "multiple-choice", "title": "More Cohesion Choices",
             "items": [
                {"id": "c2ct10", "prompt": "\"Marco preferisce il tè, Anna il caffè\" — what's omitted after Anna?", "options": ["the verb preferisce", "the subject Anna", "the object caffè"], "answerIndex": 0, "explanation": "The verb preferisce is elided, recoverable from context."},
                {"id": "c2ct11", "prompt": "Which device unambiguously refers to \"the latter\" of two just-mentioned people?", "options": ["quest'ultimo", "lui", "esso"], "answerIndex": 0, "explanation": "Quest'ultimo specifically means \"the latter\"."},
                {"id": "c2ct12", "prompt": "\"Ciò\" is best described as...", "options": ["a fixed, invariable pronoun for an abstract idea", "a masculine noun", "a verb form"], "answerIndex": 0, "explanation": "Ciò never changes for gender or number."},
                {"id": "c2ct13", "prompt": "Repeating the same full noun phrase in every sentence tends to sound...", "options": ["mechanical and unpolished", "fluent and clear", "more formal"], "answerIndex": 0, "explanation": "Constant repetition reads as unpolished in fluent writing."},
                {"id": "c2ct14", "prompt": "Ellipsis is best described as...", "options": ["the clean omission of a repeated, recoverable element", "a grammatical error", "a type of inversion"], "answerIndex": 0, "explanation": "Ellipsis omits what context already makes recoverable."},
                {"id": "c2ct15", "prompt": "When two possible antecedents exist for a pronoun, advanced writing should...", "options": ["use a demonstrative like quest'ultimo for clarity", "just pick either pronoun randomly", "always repeat the full name"], "answerIndex": 0, "explanation": "A demonstrative resolves the ambiguity explicitly."},
                {"id": "c2ct16", "prompt": "\"Tale decisione\" functions as...", "options": ["a summarizing anaphoric noun phrase", "a question", "an ellipsis"], "answerIndex": 0, "explanation": "Tale + noun summarizes something already mentioned."},
             ]},
            {"id": "c2ct-tf", "type": "true-false", "title": "True or False?",
             "items": [
                {"id": "c2ct17", "statement": "Anaphora means referring back to something already mentioned instead of repeating it.", "answer": True, "explanation": "This is exactly the definition used in this lesson."},
                {"id": "c2ct18", "statement": "Ellipsis is the addition of extra words for clarity.", "answer": False, "explanation": "Ellipsis is the omission of a repeated, recoverable element."},
                {"id": "c2ct19", "statement": "Quest'ultimo unambiguously refers to the most recently mentioned of two items.", "answer": True, "explanation": "This is quest'ultimo's specific function."},
                {"id": "c2ct20", "statement": "Ciò is invariable and doesn't change for gender or number.", "answer": True, "explanation": "Ciò is a fixed, invariable pronoun."},
                {"id": "c2ct21", "statement": "Constant repetition of the same noun phrase is a hallmark of polished writing.", "answer": False, "explanation": "It reads as mechanical and unpolished."},
                {"id": "c2ct22", "statement": "Ambiguous pronoun reference should be resolved with a demonstrative or repeated noun.", "answer": True, "explanation": "This avoids forcing the reader to guess."},
                {"id": "c2ct23", "statement": "A cohesive text always requires repeating every noun in full.", "answer": False, "explanation": "Cohesion relies on anaphora and ellipsis, not full repetition."},
             ]},
        ],
        "summary": [
            "Anaphoric devices (pronouns, ciò, quest'ultimo, summarizing nouns) avoid repeating a noun phrase across sentences.",
            "Ellipsis cleanly omits a repeated verb/phrase when grammar makes it recoverable.",
            "Ambiguous pronoun reference is resolved with demonstratives like quest'ultimo, not left to guesswork.",
        ],
    },
    {
        "id": "c2-varieta-regionale",
        "level": "C2", "unit": "1", "order": 7, "skill": "reading", "strand": "sociolinguistics",
        "title": "Italiano Regionale e Varietà",
        "subtitle": "Standard Italian isn't the only Italian — a proficient speaker recognizes the variation.",
        "objectives": [
            "Recognize that regional variation affects vocabulary, not just accent",
            "Identify a handful of well-known regionalisms and their standard equivalents",
            "Understand the sociolinguistic relationship between standard Italian and regional dialects",
        ],
        "content": {
            "intro": "Standard Italian, taught throughout this course, coexists with genuine regional varieties and dialects across Italy — true proficiency includes knowing this landscape exists, even without mastering every variety.",
            "explanation": "<p>Italy's regional dialects (Sicilian, Neapolitan, Venetian, Milanese/Lombard, Sardinian, and many more) are, linguistically, distinct languages descended independently from Latin — not simply \"accented Italian\". What most Italians actually speak day-to-day is <strong>regional Italian</strong>: standard Italian with regional vocabulary, some grammar habits, and intonation carried over from the local dialect.</p>",
            "rules": [
                {"heading": "a) Well-known regional vocabulary", "body": "<ul><li>\"What are you doing?\" — standard <em>Che fai?</em>; Roman <em>Che stai a fa'?</em></li><li>Bread roll: standard <em>panino</em>; in parts of the south, <em>panuozzo/rosetta</em> (regional bread specialties, with their own names)</li><li>Small bar snack before lunch (a well-known Northern custom): <em>aperitivo</em>, standard nationwide by now, originally strongly Milanese</li></ul>"},
                {"heading": "b) A well-known grammar habit: passato remoto in the south", "body": "<p>In much of southern Italy, the passato remoto (Lesson 2 of this level) remains common in everyday speech for recent events, where standard/northern Italian would use the passato prossimo.</p>"},
                {"heading": "c) Standard Italian's role", "body": "<p>Standard Italian (based historically on literary Florentine) is the shared language of education, media, and formal communication nationwide — the variety this entire course teaches, and the safest, most broadly understood register anywhere in Italy.</p>"},
            ],
            "examples": [
                {"it": "A Napoli si dice spesso \"jamm\" per \"andiamo\".", "en": "In Naples, \"jamm\" is often said for \"let's go\" (dialectal, not standard)."},
                {"it": "Al sud è comune sentire \"Andai al mercato stamattina\" invece di \"Sono andato\".", "en": "In the south it's common to hear the passato remoto (\"andai\") instead of the passato prossimo, even for this morning."},
                {"it": "L'italiano standard è capito e usato in tutto il Paese, anche dove si parla ancora il dialetto in famiglia.", "en": "Standard Italian is understood and used throughout the country, even where dialect is still spoken at home."},
            ],
            "commonMistakes": [
                {"wrong": "Treating regional Italian/dialect as simply \"bad\" or \"incorrect\" Italian", "right": "Recognize dialects as distinct language varieties with their own history and grammar", "why": "Italy's dialects are linguistically independent developments from Latin, not corruptions of standard Italian — a common misconception worth correcting at this level."},
            ],
        },
        "exercises": [
            {"id": "c2vr-mc", "type": "multiple-choice", "title": "Test Your Sociolinguistic Awareness",
             "items": [
                {"id": "c2vr1", "prompt": "Italy's regional dialects are best described as...", "options": ["Corrupted forms of standard Italian", "Independent language varieties descended from Latin", "Just different accents"], "answerIndex": 1, "explanation": "Dialects developed independently from Latin, parallel to standard Italian itself, not as deviations from it."},
                {"id": "c2vr2", "prompt": "In everyday southern Italian speech, which tense often replaces the passato prossimo for recent events?", "options": ["Il futuro", "Il passato remoto", "L'imperfetto"], "answerIndex": 1, "explanation": "The passato remoto remains common in everyday southern speech, unlike in the standard/northern norm."},
             ]},
            {"id": "c2vr-fill", "type": "fill-blank", "title": "More Regional Variety Practice",
             "items": [
                {"id": "c2vr3", "prompt": "L'italiano ___ è la varietà condivisa dell'istruzione e dei media.", "answers": [["standard"]], "explanation": "Standard Italian is the shared, nationwide register.", "options": ["standard", "regionale", "dialettale"]},
                {"id": "c2vr4", "prompt": "Al sud, molti usano ___ per eventi recenti, invece del passato prossimo.", "answers": [["il passato remoto"]], "explanation": "This is the well-known southern grammar habit.", "options": ["il passato remoto", "il futuro", "l'imperfetto"]},
                {"id": "c2vr5", "prompt": "I dialetti italiani derivano indipendentemente ___.", "answers": [["dal latino"]], "explanation": "Dialects are independent Latin-derived varieties, not corrupted Italian.", "options": ["dal latino", "dall'italiano standard", "dal francese"]},
                {"id": "c2vr6", "prompt": "L'___ è nato come abitudine milanese ed è diventato nazionale.", "answers": [["aperitivo"]], "explanation": "Aperitivo originated as a Milanese custom.", "options": ["aperitivo", "panino", "dialetto"]},
                {"id": "c2vr7", "prompt": "A Roma si sente spesso \"Che stai a ___?\" invece di \"Che fai?\"", "answers": [["fa'"]], "explanation": "This is a well-known Roman regionalism.", "options": ["fa'", "fare", "fai"]},
                {"id": "c2vr8", "prompt": "L'italiano standard si basa storicamente sul fiorentino ___.", "answers": [["letterario"]], "explanation": "Standard Italian is historically based on literary Florentine.", "options": ["letterario", "parlato", "antico"]},
                {"id": "c2vr9", "prompt": "I dialetti non sono forme ___ dell'italiano standard, ma varietà indipendenti.", "answers": [["corrotte"]], "explanation": "Dialects are independent varieties, not corrupted Italian.", "options": ["corrotte", "antiche", "moderne"]},
             ]},
            {"id": "c2vr-mc2", "type": "multiple-choice", "title": "More Sociolinguistic Choices",
             "items": [
                {"id": "c2vr10", "prompt": "Italy's regional dialects are linguistically best described as...", "options": ["independent varieties descended from Latin", "broken Italian", "just accents"], "answerIndex": 0, "explanation": "They developed independently from Latin, parallel to standard Italian."},
                {"id": "c2vr11", "prompt": "What do most Italians actually speak day-to-day?", "options": ["regional Italian, a blend of standard and local features", "pure standard Italian only", "pure dialect only"], "answerIndex": 0, "explanation": "Regional Italian blends standard Italian with local features."},
                {"id": "c2vr12", "prompt": "Where does the passato remoto remain common in everyday conversation?", "options": ["much of southern Italy", "exclusively in the north", "nowhere in spoken Italian"], "answerIndex": 0, "explanation": "Southern regional speech keeps it in everyday use."},
                {"id": "c2vr13", "prompt": "What is standard Italian historically based on?", "options": ["literary Florentine", "Roman dialect", "Sicilian"], "answerIndex": 0, "explanation": "Standard Italian descends from literary Florentine."},
                {"id": "c2vr14", "prompt": "Which role does standard Italian play nationwide?", "options": ["the shared language of education, media, and formal communication", "a rarely used, purely academic variety", "a regional dialect like any other"], "answerIndex": 0, "explanation": "It's the universally understood, shared register."},
                {"id": "c2vr15", "prompt": "\"Aperitivo\" as a nationwide custom originated as...", "options": ["a Milanese habit", "a Sicilian tradition", "a purely literary term"], "answerIndex": 0, "explanation": "It began as a strongly Milanese custom."},
                {"id": "c2vr16", "prompt": "Treating dialects as \"incorrect\" Italian is...", "options": ["a common misconception", "linguistically accurate", "the standard academic view"], "answerIndex": 0, "explanation": "Dialects are independent varieties, not incorrect Italian."},
             ]},
            {"id": "c2vr-tf", "type": "true-false", "title": "True or False?",
             "items": [
                {"id": "c2vr17", "statement": "Italy's dialects are simply accented versions of standard Italian.", "answer": False, "explanation": "They're independent language varieties, not accented Italian."},
                {"id": "c2vr18", "statement": "Standard Italian is the safest, most broadly understood register anywhere in Italy.", "answer": True, "explanation": "It's understood and used throughout the country."},
                {"id": "c2vr19", "statement": "The passato remoto is only found in written literature, never in speech.", "answer": False, "explanation": "It remains common in everyday southern speech."},
                {"id": "c2vr20", "statement": "Regional Italian blends standard Italian with regional vocabulary and habits.", "answer": True, "explanation": "This is exactly what regional Italian is."},
                {"id": "c2vr21", "statement": "Sicilian and Neapolitan are considered distinct language varieties by linguists.", "answer": True, "explanation": "Linguistically, they're independent developments from Latin."},
                {"id": "c2vr22", "statement": "Dialect being spoken at home means someone can't also understand standard Italian.", "answer": False, "explanation": "Standard Italian is understood nationwide, even where dialect is also spoken."},
                {"id": "c2vr23", "statement": "Proficient speakers benefit from recognizing regional variation even without mastering every variety.", "answer": True, "explanation": "Awareness of the landscape is the C2 goal, not full mastery of every dialect."},
             ]},
        ],
        "summary": [
            "Italy's dialects are distinct language varieties, not \"incorrect\" Italian — a key sociolinguistic distinction.",
            "Most Italians actually speak regional Italian day-to-day: standard Italian with regional vocabulary and habits.",
            "Standard Italian, taught throughout this course, remains the shared, universally understood register nationwide.",
        ],
    },
]
